"""Naive Bayes (multinomial) — emit log-probabilities as Python dict."""

import sys

from evals._hf import load_rows
from dispatch.primitives.cloze_features import FEATURE_NAMES, cloze_features

_MAX_TRAIN_ROWS = 2000


def _dataset():
    import numpy as np

    X: list[list[int]] = []
    y: list[int] = []
    rows = load_rows("cam-cst/cbt", "CN", split="train")
    kept = 0
    for row in rows:
        if kept >= _MAX_TRAIN_ROWS:
            break
        sentences = row.get("sentences") or []
        question = row.get("question") or ""
        options = list(row.get("options") or ())
        answer = row.get("answer") or ""
        if not question or len(options) != 10 or not answer or "XXXXX" not in question:
            continue
        prompt = (" ".join(sentences) + "\n" + question) if sentences else question
        gold = answer.strip().lower()
        added = 0
        for opt in options:
            f = cloze_features(prompt, opt)
            if f is None:
                continue
            X.append(list(f))
            y.append(1 if opt.strip().lower() == gold else 0)
            added += 1
        if added == 10:
            kept += 1
    return np.array(X, dtype=float), np.array(y, dtype=int)


def main() -> int:
    from sklearn.naive_bayes import GaussianNB

    print("loading cam-cst/cbt CN train…", file=sys.stderr)
    X, y = _dataset()
    print(f"  examples: {len(X)}", file=sys.stderr)
    nb = GaussianNB()
    nb.fit(X, y)
    means = [list(map(float, row)) for row in nb.theta_]
    vars_ = [list(map(float, row)) for row in nb.var_]
    priors = list(map(float, nb.class_prior_))
    feat_list = ", ".join(repr(n) for n in FEATURE_NAMES)
    out = (
        '"""Gaussian Naive Bayes CBT scorer — AUTOGENERATED.\n'
        "\n"
        f"Feature order: ({feat_list},)\n"
        '"""\n\n'
        "import math\n\n"
        f"CLASS_PRIORS = {priors!r}\n"
        f"FEATURE_MEAN = {means!r}\n"
        f"FEATURE_VAR  = {vars_!r}\n\n\n"
        "def score(features):\n"
        "    log_p1 = math.log(CLASS_PRIORS[1])\n"
        "    log_p0 = math.log(CLASS_PRIORS[0])\n"
        "    for i, x in enumerate(features):\n"
        "        m1, v1 = FEATURE_MEAN[1][i], max(FEATURE_VAR[1][i], 1e-9)\n"
        "        m0, v0 = FEATURE_MEAN[0][i], max(FEATURE_VAR[0][i], 1e-9)\n"
        "        log_p1 += -0.5 * ((x - m1) ** 2 / v1 + math.log(2 * math.pi * v1))\n"
        "        log_p0 += -0.5 * ((x - m0) ** 2 / v0 + math.log(2 * math.pi * v0))\n"
        "    return log_p1 - log_p0\n"
    )
    sys.stdout.write(out)
    return 0


if __name__ == "__main__":
    import sys as _sys

    _sys.exit(main())
