"""Train a Tsetlin Machine on CBT cloze features and emit boolean."""

import sys

from evals._hf import load_rows
from dispatch.primitives.cloze_features import cloze_features

_MAX_TRAIN_ROWS = 5000
_N_CLAUSES = 40
_T = 15
_S = 3.9
_EPOCHS = 20
_COUNT_THRESHOLDS = (1, 2, 3, 5)
_LEN_THRESHOLDS = (3, 5, 8, 12)


def _binarise(features: tuple[int, ...]) -> list[int]:
    tri, tri_lead, tri_trail, bg_pre, bg_post, freq, cand_len, is_stop, in_right = features
    bits: list[int] = []
    for v in (tri, tri_lead, tri_trail, bg_pre, bg_post, freq):
        bits.extend(1 if v >= t else 0 for t in _COUNT_THRESHOLDS)
    bits.extend(1 if cand_len <= t else 0 for t in _LEN_THRESHOLDS)
    bits.append(is_stop)
    bits.append(in_right)
    return bits


def _bit_names() -> list[str]:
    out: list[str] = []
    for prefix in ("tri", "tri_lead", "tri_trail", "bg_pre", "bg_post", "freq"):
        out.extend(f"{prefix}_ge{t}" for t in _COUNT_THRESHOLDS)
    out.extend(f"cand_len_le{t}" for t in _LEN_THRESHOLDS)
    out.append("is_stopword")
    out.append("in_right")
    return out


def _build_dataset():
    import numpy as np

    X: list[list[int]] = []
    y: list[int] = []
    rows = load_rows("cam-cst/cbt", "CN", split="train")
    kept = 0
    for row in rows:
        if kept >= _MAX_TRAIN_ROWS:
            break
        sentences = row.get("sentences") or []
        question = row.get("question") or ""
        options = list(row.get("options") or ())
        answer = row.get("answer") or ""
        if not question or len(options) != 10 or not answer:
            continue
        if "XXXXX" not in question:
            continue
        prompt = (" ".join(sentences) + "\n" + question) if sentences else question
        gold = answer.strip().lower()
        added = 0
        for opt in options:
            feats = cloze_features(prompt, opt)
            if feats is None:
                continue
            X.append(_binarise(feats))
            y.append(1 if opt.strip().lower() == gold else 0)
            added += 1
        if added == 10:
            kept += 1
    return np.array(X, dtype=np.uint32), np.array(y, dtype=np.uint32)


def _train(X, y):
    from pyTsetlinMachine.tm import MultiClassTsetlinMachine

    tm = MultiClassTsetlinMachine(
        number_of_clauses=_N_CLAUSES, T=_T, s=_S, weighted_clauses=True
    )
    tm.fit(X, y, epochs=_EPOCHS)
    return tm


def _emit(tm, n_features: int) -> str:
    names = _bit_names()
    bit_list = ", ".join(repr(n) for n in names)
    lines = [
        '"""Tsetlin-Machine cloze-candidate scorer — AUTOGENERATED.',
        "",
        "Trained on cam-cst/cbt CN train split via ``ml/train_tsetlin.py``.",
        "Do not hand-edit; rerun the trainer instead.",
        "",
        f"Bit order: ({bit_list},)",
        '"""',
        "",
        "",
        "def _match(bits, lits):",
        "    for f, neg in lits:",
        "        v = bits[f]",
        "        if neg:",
        "            if v: return False",
        "        else:",
        "            if not v: return False",
        "    return True",
        "",
        "",
        "def score(bits):",
        "    votes = 0",
    ]
    for cls in range(2):
        for cl in range(_N_CLAUSES):
            lits: list[tuple[int, bool]] = []
            for f in range(n_features):
                if tm.ta_action(cls, cl, f) == 1:
                    lits.append((f, False))
                if tm.ta_action(cls, cl, f + n_features) == 1:
                    lits.append((f, True))
            if not lits:
                continue
            polarity_pos = cl % 2 == 0
            # final sign: +1 if voting for class 1, -1 if voting for class 0
            voting_for_one = (cls == 1) == polarity_pos
            sign = "+" if voting_for_one else "-"
            lit_repr = ", ".join(f"({f}, {n})" for f, n in lits)
            lines.append(f"    if _match(bits, [{lit_repr}]):")
            lines.append(f"        votes {sign}= 1")
    lines.append("    return votes")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    print("loading cam-cst/cbt CN train…", file=sys.stderr)
    X, y = _build_dataset()
    print(f"  examples: {len(X)} (positives: {int(y.sum())})", file=sys.stderr)
    print("training TM…", file=sys.stderr)
    tm = _train(X, y)
    acc = (tm.predict(X) == y).mean()
    print(f"training accuracy: {acc:.4f}", file=sys.stderr)
    src = _emit(tm, n_features=X.shape[1])
    sys.stdout.write(src)
    return 0


if __name__ == "__main__":
    import sys as _sys

    _sys.exit(main())
