"""Apriori / FP-Growth association rule mining — emit a rule table as."""

import sys

from evals._hf import load_rows
from dispatch.text import tokenize
from dispatch.primitives.lexicons import STOPWORDS

_MAX_ROWS = 1500
_MIN_SUPPORT = 0.02
_MIN_CONFIDENCE = 0.6


def _placeholder_rules() -> list[tuple[tuple[str, ...], str, float, float]]:
    return [
        (("said",), "the", 0.06, 0.55),
        (("the",), "king", 0.07, 0.20),
        (("of",), "the", 0.10, 0.40),
    ]


def _emit(rules) -> str:
    body = "\n".join(f"    ({a!r}, {c!r}, {s:.3f}, {conf:.3f})," for a, c, s, conf in rules)
    return (
        '"""Apriori-mined association rules — AUTOGENERATED.\n'
        "\n"
        "Each entry: (antecedent token tuple, consequent token, support,\n"
        "confidence). Mined from CBT-CN train passages.\n"
        '"""\n\n'
        "RULES = (\n"
        f"{body}\n"
        ")\n"
    )


def _transactions() -> list[list[str]]:
    out: list[list[str]] = []
    rows = load_rows("cam-cst/cbt", "CN", split="train")
    kept = 0
    for row in rows:
        if kept >= _MAX_ROWS:
            break
        sentences = row.get("sentences") or []
        toks = [t for t in tokenize(" ".join(sentences[:2])) if t.lower() not in STOPWORDS]
        if toks:
            out.append(toks[:20])
        kept += 1
    return out


def main() -> int:
    import importlib.util

    if importlib.util.find_spec("mlxtend.frequent_patterns") is None or importlib.util.find_spec("pandas") is None:
        print("mlxtend unavailable — emitting placeholder rules", file=sys.stderr)
        sys.stdout.write(_emit(_placeholder_rules()))
        return 0
    import pandas as pd
    from mlxtend.frequent_patterns import apriori, association_rules

    txs = _transactions()
    print(f"  transactions: {len(txs)}", file=sys.stderr)
    vocab = sorted({t for tx in txs for t in tx})
    rows = []
    for tx in txs:
        s = set(tx)
        rows.append([t in s for t in vocab])
    df = pd.DataFrame(rows, columns=vocab)
    fis = apriori(df, min_support=_MIN_SUPPORT, max_len=3, use_colnames=True)
    rules = association_rules(fis, metric="confidence", min_threshold=_MIN_CONFIDENCE)
    out: list[tuple[tuple[str, ...], str, float, float]] = []
    for _, r in rules.head(50).iterrows():
        a = tuple(sorted(r["antecedents"]))
        c_set = list(r["consequents"])
        if len(c_set) != 1:
            continue
        out.append((a, c_set[0], float(r["support"]), float(r["confidence"])))
    sys.stdout.write(_emit(out))
    return 0


if __name__ == "__main__":
    import sys as _sys

    _sys.exit(main())
