"""AI Feynman — emit the discovered closed-form expression as Python."""

import sys

# Feynman eq I.6.20: Gaussian — f = exp(-theta**2 / 2) / sqrt(2*pi)
_EXPR = "math.exp(-theta**2 / 2) / math.sqrt(2 * math.pi)"


def _emit() -> str:
    return (
        '"""AI Feynman demo — AUTOGENERATED.\n'
        "\n"
        "Closed-form equation for Feynman eq I.6.20 (Gaussian PDF). The\n"
        "real pipeline discovers expressions like this from data; here\n"
        "we ship the discovered form directly to demonstrate the\n"
        "artifact shape.\n"
        '"""\n\n'
        "import math\n\n\n"
        "def gaussian_pdf(theta: float) -> float:\n"
        f"    return {_EXPR}\n"
    )


def main() -> int:
    sys.stdout.write(_emit())
    print("emitted AI Feynman demo (Gaussian PDF closed-form)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    import sys as _sys

    _sys.exit(main())
