"""Bayesian Rule Lists (Letham et al.) — emit an ordered rule list as."""

import sys

from dispatch.primitives.cloze_features import FEATURE_NAMES

_PLACEHOLDER_RULES = [
    ("tri >= 1 and bg_pre >= 1", 1),
    ("freq >= 2 and not is_stopword", 1),
    ("bg_post >= 1 and in_right == 0", 1),
    ("is_stopword == 1", 0),
    ("True", 0),
]


def _emit(rules) -> str:
    lines = [
        '"""Bayesian Rule List — AUTOGENERATED.\n'
        "\n"
        "Ordered IF-THEN-ELIF list. First matching rule wins.\n"
        '"""\n',
        f"FEATURE_NAMES = {tuple(FEATURE_NAMES)!r}",
        "",
        "",
        "def predict(features: dict) -> int:",
    ]
    for cond, cls in rules:
        lines.append(f"    if eval({cond!r}, {{'__builtins__': {{}}}}, features):")
        lines.append(f"        return {cls}")
    lines.append("    return 0")
    return "\n".join(lines) + "\n"


def main() -> int:
    sys.stdout.write(_emit(_PLACEHOLDER_RULES))
    print("emitted Bayesian Rule List placeholder", file=sys.stderr)
    return 0


if __name__ == "__main__":
    import sys as _sys

    _sys.exit(main())
