"""Mine per-question-type majority answers from NQ-open train, emit."""

import sys
from collections import Counter, defaultdict

from evals._hf import load_rows
from dispatch.primitives.nq_features import nq_question_type


def main() -> int:
    train = list(load_rows("google-research-datasets/nq_open", split="train"))
    print(f"loaded {len(train)} train rows", file=sys.stderr)
    by_type: dict[str, Counter] = defaultdict(Counter)
    for row in train:
        q = row.get("question") or ""
        answers = row.get("answer") or []
        if not q or not answers:
            continue
        gold = str(answers[0]).strip()
        if not gold:
            continue
        by_type[nq_question_type(q)][gold] += 1
    table: dict[str, str] = {}
    for t, counts in by_type.items():
        if not counts:
            continue
        best, n = counts.most_common(1)[0]
        total = sum(counts.values())
        print(
            f"  {t:14s} n={total:5d}  best={best!r}  ({n}/{total} = {n/total*100:.2f}%)",
            file=sys.stderr,
        )
        table[t] = best
    entries = ",\n".join(
        f"    {t!r}: {ans!r}" for t, ans in sorted(table.items())
    )
    out = (
        '"""Per-question-type NQ majority answers — AUTOGENERATED.\n'
        "\n"
        "Mined from ``google-research-datasets/nq_open`` train split via\n"
        "``ml/train_nq_majority.py``. Keys are buckets from\n"
        "``dispatch.primitives.nq_features.nq_question_type``;\n"
        "values are the single most-frequent gold answer per bucket.\n"
        '"""\n\n'
        "MAJORITY: dict[str, str] = {\n"
        f"{entries},\n"
        "}\n\n"
        "def lookup(qtype: str) -> str | None:\n"
        "    return MAJORITY.get(qtype)\n"
    )
    sys.stdout.write(out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
