"""Train a decision tree for CBT cloze candidate scoring and emit it."""

import os
import sys
from typing import Any

from evals._hf import load_rows
from dispatch.primitives.cloze_features import (
    FEATURE_NAMES,
    cloze_features,
)

_MAX_TRAIN_ROWS = int(os.environ.get("CBT_ROWS", "5000"))
_TREE_MAX_DEPTH = int(os.environ.get("CBT_DEPTH", "7"))
_TREE_LEAVES = int(os.environ.get("CBT_LEAF", "200"))
_TREE_TREES = int(os.environ.get("CBT_TREES", "8"))
_TREE_WEIGHT = float(os.environ.get("CBT_WEIGHT", "20.0"))


def _build_dataset(config: str) -> tuple[list[list[int]], list[int]]:
    X: list[list[int]] = []
    y: list[int] = []
    rows = load_rows("cam-cst/cbt", config, split="train")
    kept = 0
    for row in rows:
        if kept >= _MAX_TRAIN_ROWS:
            break
        sentences = row.get("sentences") or []
        question = row.get("question") or ""
        options = list(row.get("options") or ())
        answer = row.get("answer") or ""
        if not question or len(options) != 10 or not answer:
            continue
        if "XXXXX" not in question:
            continue
        prompt = (" ".join(sentences).strip() + "\n" + question) if sentences else question
        gold = answer.strip().lower()
        added = 0
        for opt in options:
            feats = cloze_features(prompt, opt)
            if feats is None:
                continue
            X.append(list(feats))
            y.append(1 if opt.strip().lower() == gold else 0)
            added += 1
        if added == 10:
            kept += 1
    return X, y


def _train(X: list[list[int]], y: list[int]) -> Any:
    from sklearn.ensemble import RandomForestClassifier

    clf = RandomForestClassifier(
        n_estimators=_TREE_TREES,
        max_depth=_TREE_MAX_DEPTH,
        min_samples_leaf=_TREE_LEAVES,
        class_weight={0: 1.0, 1: _TREE_WEIGHT},
        random_state=int(os.environ.get("CBT_SEED", "0")),
        n_jobs=1,
    )
    clf.fit(X, y)
    return clf


def _emit(config: str, clf: Any) -> str:
    import m2cgen

    body = m2cgen.export_to_python(clf, function_name="_raw_score")
    feature_list = ", ".join(repr(n) for n in FEATURE_NAMES)
    header = (
        '"""Decision-tree CBT candidate scorer — AUTOGENERATED.\n'
        f"\n"
        f"Trained on cam-cst/cbt config={config!r} train split via\n"
        f"``ml/train_cbt_tree.py``. Do not hand-edit; rerun the\n"
        f"trainer instead.\n"
        f"\n"
        f"Feature order: ({feature_list},)\n"
        '"""\n\n'
    )
    runtime = (
        "\n\n"
        "def score(features):\n"
        "    raw = _raw_score(list(features))\n"
        "    # m2cgen returns a list [P(0), P(1)] for tree classifiers.\n"
        "    return raw[1] if isinstance(raw, list) and len(raw) == 2 else float(raw)\n"
    )
    return header + body + runtime


def main() -> int:
    config = sys.argv[1] if len(sys.argv) > 1 else "CN"
    if config not in {"CN", "NE", "ALL"}:
        print(f"unknown config {config!r}; use CN, NE, or ALL", file=sys.stderr)
        return 2
    if config == "ALL":
        print("loading cam-cst/cbt train (CN + NE)…", file=sys.stderr)
        Xc, yc = _build_dataset("CN")
        Xn, yn = _build_dataset("NE")
        X = Xc + Xn
        y = yc + yn
    else:
        print(f"loading cam-cst/cbt config={config} train split…", file=sys.stderr)
        X, y = _build_dataset(config)
    print(f"  examples: {len(X)} (positives: {sum(y)})", file=sys.stderr)
    clf = _train(X, y)
    print(f"training accuracy: {clf.score(X, y):.4f}", file=sys.stderr)
    src = _emit(config, clf)
    sys.stdout.write(src)
    return 0


if __name__ == "__main__":
    import sys as _sys

    _sys.exit(main())
