"""Logic Regression — Ruczinski et al. (2003)."""

import sys

_PLACEHOLDER = '''"""Logic regression — AUTOGENERATED demo.

Score = intercept + sum(coef_i * L_i(features))
where each L_i is a boolean expression evaluated on the features.
"""

INTERCEPT = -0.4

# Each row: (boolean expression string, coefficient)
LOGIC_TERMS = (
    ("(tri >= 1) and (bg_pre >= 1)",                            1.45),
    ("(freq >= 2) and not (is_stopword == 1)",                  0.82),
    ("(tri_lead >= 1) or (tri_trail >= 1)",                     0.55),
    ("(in_right == 1)",                                         -0.91),
    ("(is_stopword == 1)",                                      -0.68),
)


def score(features: dict) -> float:
    total = INTERCEPT
    for expr, coef in LOGIC_TERMS:
        from contextlib import suppress
        _hit = [False]
        with suppress(Exception):
            _hit[0] = bool(eval(expr, {"__builtins__": {}}, features))
        if _hit[0]:
            total += coef
    return total
'''


def main() -> int:
    sys.stdout.write(_PLACEHOLDER)
    print("emitted Logic Regression demo", file=sys.stderr)
    return 0


if __name__ == "__main__":
    import sys as _sys

    _sys.exit(main())
