"""Neural-Backed Decision Tree — emit the *label hierarchy* portion as."""

import sys

_HIERARCHY = {
    "root": ["vehicle", "animal"],
    "vehicle": ["car", "truck", "bicycle"],
    "animal": ["mammal", "bird"],
    "mammal": ["dog", "cat", "horse"],
    "bird": ["sparrow", "eagle"],
}


def _emit() -> str:
    return (
        '"""NBDT-shaped class hierarchy — AUTOGENERATED.\n'
        "\n"
        "Only the tree-on-top is exported; the CNN backbone is out of\n"
        "scope for a code-as-output project. The hierarchy below is\n"
        "diff-reviewable and editable.\n"
        '"""\n\n'
        f"HIERARCHY: dict[str, list[str]] = {_HIERARCHY!r}\n\n\n"
        "def is_descendant(node: str, descendant: str) -> bool:\n"
        "    if descendant == node:\n"
        "        return True\n"
        "    for child in HIERARCHY.get(node, ()):\n"
        "        if is_descendant(child, descendant):\n"
        "            return True\n"
        "    return False\n"
    )


def main() -> int:
    sys.stdout.write(_emit())
    print("emitted NBDT class hierarchy", file=sys.stderr)
    return 0


if __name__ == "__main__":
    import sys as _sys

    _sys.exit(main())
