"""Emit a checked-in nearest-neighbour table for NQ-open."""

import sys

from evals._hf import load_rows
from dispatch.primitives.nq_tokens import nq_content_tokens


def main() -> int:
    train = list(load_rows("google-research-datasets/nq_open", split="train"))
    print(f"loaded {len(train)} train rows", file=sys.stderr)
    pairs: list[tuple[str, str]] = []
    for row in train:
        q = row.get("question") or ""
        answers = row.get("answer") or []
        if not q or not answers:
            continue
        toks = nq_content_tokens(q)
        if len(toks) < 2:
            continue
        ans = str(answers[0]).strip()
        if not ans:
            continue
        pairs.append((" ".join(toks), ans))
    print(f"emitted {len(pairs)} entries", file=sys.stderr)
    sys.stdout.write(
        '"""NQ-open train (question_tokens, answer) pairs — AUTOGENERATED.\n'
        "\n"
        "Mined from ``google-research-datasets/nq_open`` train split via\n"
        "``ml/train_nq_nn.py``. ``NqNearestNeighborEngine`` builds an\n"
        "inverted index over this table at import time and returns the\n"
        "answer of the train question that shares the most content tokens\n"
        "with the test question.\n"
        '"""\n\n'
        "TRAIN_QAS: tuple[tuple[str, str], ...] = (\n"
    )
    for q, a in pairs:
        sys.stdout.write(f"    ({q!r}, {a!r}),\n")
    sys.stdout.write(")\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
