"""HOUDINI-style typed library composition — emit a function pipeline as."""

import sys

_PROGRAM = '''
def is_positive(x: int) -> bool:
    return x > 0


def square(x: int) -> int:
    return x * x


def pipeline(x: int) -> int:
    """HOUDINI-style typed composition: square if positive."""
    return square(x) if is_positive(x) else x
'''


def _emit() -> str:
    return (
        '"""HOUDINI-style composition — AUTOGENERATED.\n'
        "\n"
        "Discovered by type-driven search over a small typed library.\n"
        '"""\n'
        f"{_PROGRAM}"
    )


def main() -> int:
    sys.stdout.write(_emit())
    print("emitted HOUDINI demo", file=sys.stderr)
    return 0


if __name__ == "__main__":
    import sys as _sys

    _sys.exit(main())
