"""Train a Random Forest for WSC pronoun resolution and emit it as."""

import sys

from evals._hf import load_rows
from dispatch.primitives.wsc_features import FEATURE_NAMES, wsc_features


def main() -> int:
    import m2cgen
    import numpy as np
    from sklearn.ensemble import RandomForestClassifier

    train = list(load_rows("super_glue", "wsc", split="train"))
    print(f"loaded {len(train)} train rows", file=sys.stderr)
    Xtr = np.array([wsc_features(r["text"], r["span1_text"], r["span2_text"]) for r in train])
    ytr = np.array([int(r["label"]) for r in train])

    clf = RandomForestClassifier(
        n_estimators=32,
        max_depth=5,
        min_samples_leaf=10,
        random_state=0,
        n_jobs=1,
    )
    clf.fit(Xtr, ytr)
    print(f"training accuracy: {clf.score(Xtr, ytr):.4f}", file=sys.stderr)

    body = m2cgen.export_to_python(clf, function_name="_raw_score")
    feature_list = ", ".join(repr(n) for n in FEATURE_NAMES)
    out = (
        '"""Random-forest WSC referent classifier — AUTOGENERATED.\n'
        "\n"
        "Trained on super_glue/wsc train split via ``ml/train_wsc_tree.py``.\n"
        "Predicts 1 if span1 is the referent of span2, else 0.\n"
        "\n"
        f"Feature order: ({feature_list},)\n"
        '"""\n\n'
        f"{body}\n\n"
        "def predict(features) -> int:\n"
        "    raw = _raw_score(list(features))\n"
        "    p1 = raw[1] if isinstance(raw, list) and len(raw) == 2 else float(raw)\n"
        "    return 1 if p1 >= 0.5 else 0\n"
    )
    sys.stdout.write(out)
    return 0


if __name__ == "__main__":
    import sys as _sys

    _sys.exit(main())
