"""Soft Decision Trees — Frosst & Hinton 2017."""

import sys

_PLACEHOLDER = '''"""Hardened Soft Decision Tree — AUTOGENERATED demo.

Distilled from a 3-level soft tree trained on (features → label)
pairs. Internal nodes use linear hyperplanes ``w · x > b``; at
inference each hyperplane is hardened to a discrete gate.
"""

NODES = {
    # (name): (left_child, right_child, weights, bias)
    "root":  ("L1", "R1", {"tri": 0.7, "bg_pre": 0.4}, 0.5),
    "L1":    ("L2", "leaf_a", {"freq": 0.6}, 1.5),
    "R1":    ("leaf_b", "leaf_c", {"is_stopword": -1.0}, -0.5),
    "L2":    ("leaf_d", "leaf_e", {"bg_post": 0.5}, 0.5),
}

LEAVES = {
    "leaf_a": [0.2, 0.8],
    "leaf_b": [0.3, 0.7],
    "leaf_c": [0.9, 0.1],
    "leaf_d": [0.1, 0.9],
    "leaf_e": [0.7, 0.3],
}


def predict_proba(features: dict) -> list[float]:
    node = "root"
    while node in NODES:
        left, right, weights, bias = NODES[node]
        s = sum(features.get(k, 0) * w for k, w in weights.items())
        node = right if s > bias else left
    return LEAVES[node]


def predict(features: dict) -> int:
    p = predict_proba(features)
    return p.index(max(p))
'''


def main() -> int:
    sys.stdout.write(_PLACEHOLDER)
    print("emitted Soft Decision Tree demo", file=sys.stderr)
    return 0


if __name__ == "__main__":
    import sys as _sys

    _sys.exit(main())
