"""∂ILP (differentiable Inductive Logic Programming) — emit Horn."""

import sys

_DATALOG = """
edge(a, b).
edge(b, c).
edge(c, d).

connected(X, Y) :- edge(X, Y).
connected(X, Y) :- edge(X, Z), connected(Z, Y).
"""


def _emit() -> str:
    return (
        '"""∂ILP-shaped Datalog rule export — AUTOGENERATED.\n'
        "\n"
        "Original program below; Python translation provided as the\n"
        "runtime predicate.\n"
        '"""\n\n'
        f"DATALOG_PROGRAM = {_DATALOG.strip()!r}\n\n\n"
        "_EDGES = (('a','b'), ('b','c'), ('c','d'))\n\n\n"
        "def _edge(x, y) -> bool:\n"
        "    return (x, y) in _EDGES\n\n\n"
        "def connected(x: str, y: str, _seen: frozenset[str] = frozenset()) -> bool:\n"
        "    if _edge(x, y):\n"
        "        return True\n"
        "    if x in _seen:\n"
        "        return False\n"
        "    return any(\n"
        "        connected(z, y, _seen | {x})\n"
        "        for (a, z) in _EDGES if a == x\n"
        "    )\n"
    )


def main() -> int:
    sys.stdout.write(_emit())
    print("emitted ∂ILP demo (handwritten Datalog → Python)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    import sys as _sys

    _sys.exit(main())
