"""Logical Neural Network (IBM LNN) — emit a weighted-logic formula."""

import sys

_FORMULA: dict = {
    "op": "and",
    "weight": 1.0,
    "operands": [
        {"op": "lit", "name": "is_dialog", "weight": 0.8},
        {"op": "or", "weight": 0.9, "operands": [
            {"op": "lit", "name": "ends_with_comma", "weight": 0.7},
            {"op": "lit", "name": "ends_with_excl",  "weight": 0.4},
        ]},
    ],
}


def _emit() -> str:
    return (
        '"""LNN-shaped weighted-logic formula — AUTOGENERATED.\n'
        "\n"
        "Output of an LNN-style trainer: a tree of logical connectives\n"
        "with per-node weights. Not pure code but diff-reviewable as\n"
        "structured Python data.\n"
        '"""\n\n'
        f"FORMULA = {_FORMULA!r}\n\n\n"
        "def evaluate(facts: dict[str, bool]) -> float:\n"
        "    def walk(node):\n"
        "        if node['op'] == 'lit':\n"
        "            return node['weight'] if facts.get(node['name']) else 0.0\n"
        "        vs = [walk(c) for c in node['operands']]\n"
        "        if node['op'] == 'and':\n"
        "            return node['weight'] * min(vs)\n"
        "        if node['op'] == 'or':\n"
        "            return node['weight'] * max(vs)\n"
        "        return 0.0\n"
        "    return walk(FORMULA)\n"
    )


def main() -> int:
    sys.stdout.write(_emit())
    print("emitted LNN demo formula tree", file=sys.stderr)
    return 0


if __name__ == "__main__":
    import sys as _sys

    _sys.exit(main())
