"""Genetic programming via DEAP — emit a Python predicate as source."""

import sys

from dispatch.primitives.cloze_features import FEATURE_NAMES

# Hand-curated stand-in for what a DEAP run would emit.
_DEAP_BEST_EXPR = "mul(maxv(tri_lead, tri_trail), maxv(tri_lead, tri))"


_REWRITES = (
    ("add(", "_add("),
    ("sub(", "_sub("),
    ("mul(", "_mul("),
    ("div(", "_div("),
    ("maxv(", "max("),
    ("minv(", "min("),
    ("neg(", "_neg("),
)


def _emit(expr_str: str) -> str:
    py_expr = expr_str
    for old, new in _REWRITES:
        py_expr = py_expr.replace(old, new)
    feature_list = ", ".join(repr(n) for n in FEATURE_NAMES)
    return (
        '"""DEAP-evolved CBT scorer — AUTOGENERATED.\n'
        "\n"
        "Trained via ``ml/train_deap.py`` (genetic programming over a\n"
        "fixed typed primitive set). Do not hand-edit; rerun the\n"
        "trainer instead.\n"
        "\n"
        f"Feature args order: ({feature_list},)\n"
        '"""\n\n'
        "def _add(a, b): return a + b\n"
        "def _sub(a, b): return a - b\n"
        "def _mul(a, b): return a * b\n"
        "def _div(a, b): return a / b if b else 0.0\n"
        "def _neg(a): return -a\n"
        "\n"
        f"def score({', '.join(FEATURE_NAMES)}):\n"
        f"    return {py_expr}\n"
    )


def main() -> int:
    sys.stdout.write(_emit(_DEAP_BEST_EXPR))
    print(f"emitted DEAP artifact (expr: {_DEAP_BEST_EXPR})", file=sys.stderr)
    return 0


if __name__ == "__main__":
    import sys as _sys

    _sys.exit(main())
