"""FunSearch-style program evolution — emit the winning Python function."""

import sys

from evals._hf import load_rows
from dispatch.primitives.cloze_features import FEATURE_NAMES, cloze_features

_MAX_TRAIN_ROWS = 300


_CANDIDATES = [
    # Each entry: (template, body-Python). The template is what gets
    # written to the artifact; the body-Python is what we evaluate.
    ("trigram first",      "tri * 3 + tri_lead + tri_trail + bg_pre + bg_post + freq"),
    ("trigram heavy",      "tri * 5 + tri_lead * 2 + tri_trail * 2 + bg_pre + bg_post + 0.5 * freq"),
    ("bigram first",       "bg_pre * 2 + bg_post * 2 + tri + freq"),
    ("freq + trigram",     "freq * 2 + tri + tri_lead + tri_trail"),
    ("anti-stopword",      "(tri + bg_pre + bg_post + freq) * (1 - is_stopword) - in_right * 2"),
    ("length-weighted",    "(tri + bg_pre + bg_post) * (1.0 if cand_len > 3 else 0.5)"),
]


def _eval_score(body: str, X, y) -> float:
    """Each prompt contributes 10 candidates; we predict the argmax
    candidate per prompt and compute top-1 accuracy.
    """
    correct = 0
    n_prompts = 0
    for group in _grouped(X, y):
        best_idx = -1
        best_score = -1e30
        for i, x in enumerate(group["X"]):
            ns = dict(zip(FEATURE_NAMES, x))
            score = eval(body, {"__builtins__": {}}, ns)
            if score > best_score:
                best_score = score
                best_idx = i
        if best_idx >= 0 and group["y"][best_idx] == 1:
            correct += 1
        n_prompts += 1
    return correct / max(1, n_prompts)


def _grouped(X, y):
    g = {"X": [], "y": []}
    for i, (xv, yv) in enumerate(zip(X, y)):
        g["X"].append(xv)
        g["y"].append(yv)
        if len(g["X"]) == 10:
            yield g
            g = {"X": [], "y": []}


def _dataset():
    X: list[list[int]] = []
    y: list[int] = []
    rows = load_rows("cam-cst/cbt", "CN", split="train")
    kept = 0
    for row in rows:
        if kept >= _MAX_TRAIN_ROWS:
            break
        sentences = row.get("sentences") or []
        question = row.get("question") or ""
        options = list(row.get("options") or ())
        answer = row.get("answer") or ""
        if not question or len(options) != 10 or not answer:
            continue
        if "XXXXX" not in question:
            continue
        prompt = (" ".join(sentences) + "\n" + question) if sentences else question
        gold = answer.strip().lower()
        added = 0
        for opt in options:
            feats = cloze_features(prompt, opt)
            if feats is None:
                continue
            X.append(list(feats))
            y.append(1 if opt.strip().lower() == gold else 0)
            added += 1
        if added == 10:
            kept += 1
    return X, y


def _emit(label: str, body: str, accuracy: float) -> str:
    args = ", ".join(FEATURE_NAMES)
    return (
        '"""FunSearch-style winning scorer — AUTOGENERATED.\n'
        "\n"
        "Selected from a small fixed pool of candidate Python bodies via\n"
        "``ml/train_funsearch.py``. The real FunSearch loop adds LLM-\n"
        "generated proposals to this pool.\n"
        "\n"
        f"Winner: {label!r}\n"
        f"Top-1 CBT-CN train acc: {accuracy:.3f}\n"
        '"""\n\n'
        f"def score({args}):\n"
        f"    return {body}\n"
    )


def main() -> int:
    print("loading cam-cst/cbt CN train…", file=sys.stderr)
    X, y = _dataset()
    print(f"  examples: {len(X)} → {len(X)//10} prompts", file=sys.stderr)
    best_label = best_body = None
    best_acc = -1.0
    for label, body in _CANDIDATES:
        acc = _eval_score(body, X, y)
        print(f"  {label:18s} acc={acc:.3f}", file=sys.stderr)
        if acc > best_acc:
            best_acc = acc
            best_label = label
            best_body = body
    sys.stdout.write(_emit(best_label, best_body, best_acc))
    return 0


if __name__ == "__main__":
    import sys as _sys

    _sys.exit(main())
