"""Sum-Product Network (SPFlow) — emit a Python graph builder."""

import sys


def _placeholder() -> str:
    return (
        '"""SPN graph — AUTOGENERATED via ``ml/train_spn.py``.\n'
        "\n"
        "Without SPFlow installed the trainer emits this placeholder\n"
        "showing the shape of the artifact: a Python builder that\n"
        "constructs the SPN graph from sum/product/leaf nodes.\n"
        '"""\n\n'
        "def build():\n"
        "    # Real form:\n"
        "    #   from spn.structure.Base import Sum, Product\n"
        "    #   from spn.structure.leaves.parametric.Parametric import Gaussian\n"
        "    #   leaf_a = Gaussian(mean=0.4, stdev=0.1, scope=0)\n"
        "    #   leaf_b = Gaussian(mean=2.5, stdev=0.5, scope=1)\n"
        "    #   prod   = Product(children=[leaf_a, leaf_b])\n"
        "    #   spn    = Sum(weights=[0.4, 0.6], children=[prod, ...])\n"
        "    return None\n"
    )


def _emit_real() -> str | None:
    import importlib.util

    if importlib.util.find_spec("spn.structure.Base") is None:
        return None
    # Demonstration: tiny hand-built SPN; LearnSPN would replace this.
    return (
        '"""SPFlow SPN graph — AUTOGENERATED.\n'
        '"""\n\n'
        "from spn.structure.Base import Product, Sum\n"
        "from spn.structure.leaves.parametric.Parametric import Gaussian\n\n\n"
        "def build():\n"
        "    leaf_a = Gaussian(mean=0.4, stdev=0.1, scope=0)\n"
        "    leaf_b = Gaussian(mean=2.5, stdev=0.5, scope=1)\n"
        "    prod   = Product(children=[leaf_a, leaf_b])\n"
        "    return Sum(weights=[1.0], children=[prod])\n"
    )


def main() -> int:
    src = _emit_real() or _placeholder()
    sys.stdout.write(src)
    print("emitted SPN artifact (real spn module present? "
          + str(_emit_real() is not None) + ")", file=sys.stderr)
    return 0


if __name__ == "__main__":
    import sys as _sys

    _sys.exit(main())
