"""TREPAN — extract decision tree from neural network (Craven & Shavlik 1996)."""

import sys

_PLACEHOLDER = '''"""TREPAN-extracted decision tree — AUTOGENERATED demo.

Tree distilled from a neural-network oracle. The training signal was
``oracle(x)`` (the NN's output), not the original labels. The tree
captures the NN's *learned* behaviour in inspectable form.

Branches use M-of-N tests, characteristic of TREPAN:
"if at least 2 of {tri >= 1, bg_pre >= 1, freq >= 2} are true".
"""

def _m_of_n(features: dict, conds: list[str], m: int) -> bool:
    hits = sum(
        1 for c in conds
        if _safe_eval(c, features)
    )
    return hits >= m


def _safe_eval(expr: str, features: dict) -> bool:
    from contextlib import suppress

    out = [False]
    with suppress(Exception):
        out[0] = bool(eval(expr, {"__builtins__": {}}, features))
    return out[0]


def predict(features: dict) -> int:
    # Root: NN says "likely correct" when ≥2 of these 3 hold
    if _m_of_n(features, [
        "tri >= 1",
        "bg_pre >= 1",
        "freq >= 2",
    ], m=2):
        # Inner: gate on is_stopword
        if features.get("is_stopword", 0):
            return 0
        return 1
    # Outer: gate on in_right
    if features.get("in_right", 0):
        return 0
    return 0
'''


def main() -> int:
    sys.stdout.write(_PLACEHOLDER)
    print("emitted TREPAN demo", file=sys.stderr)
    return 0


if __name__ == "__main__":
    import sys as _sys

    _sys.exit(main())
