"""DSO / uDSR (Deep Symbolic Optimization) — emit the discovered sympy."""

import sys

_EXPR = "x0 * math.sin(x1) + math.log(1 + x2**2)"


def _emit() -> str:
    return (
        '"""DSO-style expression — AUTOGENERATED.\n'
        "\n"
        "Sample of the kind of closed-form expression DSO discovers via\n"
        "risk-seeking policy-gradient over expression tokens.\n"
        '"""\n\n'
        "import math\n\n\n"
        "def score(x0, x1, x2):\n"
        f"    return {_EXPR}\n"
    )


def main() -> int:
    sys.stdout.write(_emit())
    print("emitted DSO placeholder expression", file=sys.stderr)
    return 0


if __name__ == "__main__":
    import sys as _sys

    _sys.exit(main())
