"""CLEAR — Counterfactual Local Explanations as Rules (Antoran 2021)."""

import sys

_PLACEHOLDER = '''"""CLEAR counterfactual rule book — AUTOGENERATED demo.

Each entry: (positive condition, suggested edit to flip prediction).
"""

CLEAR_RULES = (
    ("tri >= 1",
     "raise tri to >= 2"),
    ("bg_pre == 0",
     "ensure at least one bigram match"),
    ("is_stopword == 1",
     "candidate must not be a stopword"),
    ("freq < 2",
     "candidate must appear at least twice in the passage"),
)


def suggestions_to_flip(features: dict) -> list[str]:
    """Return human-readable edits that would flip the prediction."""
    edits = []
    for cond, edit in CLEAR_RULES:
        from contextlib import suppress
        _hit = [False]
        with suppress(Exception):
            _hit[0] = bool(eval(cond, {"__builtins__": {}}, features))
        if _hit[0]:
            edits.append(edit)
    return edits
'''


def main() -> int:
    sys.stdout.write(_PLACEHOLDER)
    print("emitted CLEAR demo", file=sys.stderr)
    return 0


if __name__ == "__main__":
    import sys as _sys

    _sys.exit(main())
