"""DeepProbLog-style probabilistic logic program — emit ProbLog text +."""

import sys

_PROGRAM = """
0.7::heads(Coin).
both_heads(C1, C2) :- heads(C1), heads(C2).
"""


def _emit() -> str:
    return (
        '"""DeepProbLog-style program — AUTOGENERATED.\n'
        "\n"
        "Probabilistic rules in ProbLog text + a Python mock evaluator.\n"
        '"""\n\n'
        f"PROBLOG = {_PROGRAM.strip()!r}\n\n\n"
        "def probability_both_heads(p_heads_1: float, p_heads_2: float) -> float:\n"
        "    return p_heads_1 * p_heads_2\n"
    )


def main() -> int:
    sys.stdout.write(_emit())
    print("emitted DeepProbLog demo", file=sys.stderr)
    return 0


if __name__ == "__main__":
    import sys as _sys

    _sys.exit(main())
