"""Pylon — emit constraints-as-Python-functions wired to a differentiable."""

import sys

_CONSTRAINTS = '''
def at_least_one_positive(label_probs: list[float]) -> bool:
    """Pylon constraint: at least one class must have non-trivial mass."""
    return max(label_probs) > 0.5


def labels_sum_to_one(label_probs: list[float]) -> bool:
    return abs(sum(label_probs) - 1.0) < 1e-3
'''


def _emit() -> str:
    return (
        '"""Pylon constraints — AUTOGENERATED.\n'
        "\n"
        "Pylon compiles Python predicate functions to a differentiable\n"
        "loss; the artifact is the constraint set itself.\n"
        '"""\n'
        f"{_CONSTRAINTS}\n"
    )


def main() -> int:
    sys.stdout.write(_emit())
    print("emitted Pylon constraints demo", file=sys.stderr)
    return 0


if __name__ == "__main__":
    import sys as _sys

    _sys.exit(main())
