"""K-NN with k=1 prototypes — memorize representative feature vectors."""

import sys

from evals._hf import load_rows
from dispatch.primitives.cloze_features import FEATURE_NAMES, cloze_features

_MAX_TRAIN_ROWS = 2000
_NUM_PROTOTYPES = 32


def _dataset():
    import numpy as np

    X: list[list[int]] = []
    y: list[int] = []
    rows = load_rows("cam-cst/cbt", "CN", split="train")
    kept = 0
    for row in rows:
        if kept >= _MAX_TRAIN_ROWS:
            break
        sentences = row.get("sentences") or []
        question = row.get("question") or ""
        options = list(row.get("options") or ())
        answer = row.get("answer") or ""
        if not question or len(options) != 10 or not answer or "XXXXX" not in question:
            continue
        prompt = (" ".join(sentences) + "\n" + question) if sentences else question
        gold = answer.strip().lower()
        for opt in options:
            f = cloze_features(prompt, opt)
            if f is None:
                continue
            X.append(list(f))
            y.append(1 if opt.strip().lower() == gold else 0)
        kept += 1
    return np.array(X, dtype=float), np.array(y, dtype=int)


def main() -> int:
    from collections import Counter

    from sklearn.cluster import KMeans

    print("loading cam-cst/cbt CN train…", file=sys.stderr)
    X, y = _dataset()
    print(f"  examples: {len(X)}", file=sys.stderr)
    km = KMeans(n_clusters=_NUM_PROTOTYPES, random_state=0, n_init=10)
    km.fit(X)
    centroids = km.cluster_centers_
    labels = km.predict(X)
    prototypes: list[tuple[list[float], int]] = []
    for k in range(_NUM_PROTOTYPES):
        members = [int(y[i]) for i in range(len(y)) if labels[i] == k]
        if not members:
            continue
        most_common = Counter(members).most_common(1)[0][0]
        prototypes.append((list(map(float, centroids[k])), most_common))
    feat_list = ", ".join(repr(n) for n in FEATURE_NAMES)
    proto_repr = ",\n    ".join(
        f"({fv!r}, {lbl})" for fv, lbl in prototypes
    )
    out = (
        '"""K-NN (k=1) CBT scorer — AUTOGENERATED.\n'
        "\n"
        "Cluster-centroid prototypes. Inference walks PROTOTYPES, picks the\n"
        "nearest by L2 distance, and returns 1 if the prototype's label\n"
        "is 1.\n"
        "\n"
        f"Feature order: ({feat_list},)\n"
        '"""\n\n'
        "PROTOTYPES: tuple[tuple[tuple[float, ...], int], ...] = (\n"
        f"    {proto_repr},\n"
        ")\n\n\n"
        "def score(features):\n"
        "    best_dist = float('inf')\n"
        "    best_lbl = 0\n"
        "    for proto, lbl in PROTOTYPES:\n"
        "        d = sum((f - p) ** 2 for f, p in zip(features, proto))\n"
        "        if d < best_dist:\n"
        "            best_dist = d\n"
        "            best_lbl = lbl\n"
        "    return 1.0 if best_lbl == 1 else 0.0\n"
    )
    sys.stdout.write(out)
    return 0


if __name__ == "__main__":
    import sys as _sys

    _sys.exit(main())
