"""Aleph — classical ILP system (Srinivasan 2001)."""

import sys

_PROLOG = """
% Background: parent/2, male/1
% Learned: father(X, Y) :- parent(X, Y), male(X).

father(X, Y) :- parent(X, Y), male(X).
"""


def _emit() -> str:
    return (
        '"""Aleph ILP-learned predicate — AUTOGENERATED demo.\n'
        "\n"
        "Prolog source from Aleph + Python predicate translation.\n"
        '"""\n\n'
        f"PROLOG = {_PROLOG.strip()!r}\n\n\n"
        "PARENT = {('alice', 'bob'), ('carol', 'dave')}\n"
        "MALE = {'bob', 'dave'}\n\n\n"
        "def father(x: str, y: str) -> bool:\n"
        "    return (x, y) in PARENT and x in MALE\n"
    )


def main() -> int:
    sys.stdout.write(_emit())
    print("emitted Aleph demo", file=sys.stderr)
    return 0


if __name__ == "__main__":
    import sys as _sys

    _sys.exit(main())
