"""CN2 sequential covering rule learner — emit ordered IF-THEN-ELIF."""

import sys

_PLACEHOLDER_RULES = [
    ("tri >= 1 and bg_pre >= 1", 1),
    ("tri_lead >= 1 and is_stopword == 0", 1),
    ("freq >= 2 and bg_post >= 1", 1),
    ("in_right == 1", 0),
    ("is_stopword == 1 and freq <= 1", 0),
    ("True", 0),
]


def _emit(rules) -> str:
    body = []
    for cond, cls in rules:
        body.append(f"    if eval({cond!r}, {{'__builtins__': {{}}}}, features):")
        body.append(f"        return {cls}")
    return (
        '"""CN2 sequential covering rule list — AUTOGENERATED.\n'
        "\n"
        "Highest-information-gain rule first; first matching rule wins.\n"
        '"""\n\n'
        "def predict(features: dict) -> int:\n"
        + "\n".join(body)
        + "\n    return 0\n"
    )


def main() -> int:
    sys.stdout.write(_emit(_PLACEHOLDER_RULES))
    print("emitted CN2 demo", file=sys.stderr)
    return 0


if __name__ == "__main__":
    import sys as _sys

    _sys.exit(main())
