"""Train a small decision-tree forest, then compile its DNF into a."""

import sys

from evals._hf import load_rows
from dispatch.primitives.cloze_features import cloze_features

_MAX_TRAIN_ROWS = 1500


def _bits(features):
    tri, tri_lead, tri_trail, bg_pre, bg_post, freq, cand_len, is_stop, in_right = features
    return [
        1 if tri > 0 else 0,
        1 if bg_pre > 0 else 0,
        1 if bg_post > 0 else 0,
        1 if freq > 0 else 0,
        is_stop,
        in_right,
    ]


_BIT_NAMES = ("tri_pos", "bg_pre_pos", "bg_post_pos", "freq_pos", "is_stop", "in_right")


def _dataset():
    X: list[list[int]] = []
    y: list[int] = []
    rows = load_rows("cam-cst/cbt", "CN", split="train")
    kept = 0
    for row in rows:
        if kept >= _MAX_TRAIN_ROWS:
            break
        sentences = row.get("sentences") or []
        question = row.get("question") or ""
        options = list(row.get("options") or ())
        answer = row.get("answer") or ""
        if not question or len(options) != 10 or not answer:
            continue
        if "XXXXX" not in question:
            continue
        prompt = (" ".join(sentences) + "\n" + question) if sentences else question
        gold = answer.strip().lower()
        added = 0
        for opt in options:
            feats = cloze_features(prompt, opt)
            if feats is None:
                continue
            X.append(_bits(feats))
            y.append(1 if opt.strip().lower() == gold else 0)
            added += 1
        if added == 10:
            kept += 1
    return X, y


def _learn_tree(X, y):
    from sklearn.tree import DecisionTreeClassifier

    clf = DecisionTreeClassifier(max_depth=4, min_samples_leaf=50, random_state=0)
    clf.fit(X, y)
    return clf


def _tree_paths(clf):
    """Return list of (literal_list, leaf_class) for every accepting path."""
    tree = clf.tree_
    paths: list[tuple[list[tuple[int, bool]], int]] = []

    def walk(node: int, lits: list[tuple[int, bool]]):
        if tree.children_left[node] == -1:
            cls = int(tree.value[node].argmax())
            paths.append((list(lits), cls))
            return
        feat = int(tree.feature[node])
        # Tree splits on feature <= 0.5 → left is "feat = 0", right is "feat = 1"
        walk(tree.children_left[node], lits + [(feat, True)])  # negated
        walk(tree.children_right[node], lits + [(feat, False)])

    walk(0, [])
    return paths


def _minimise(paths_for_class1) -> str:
    from dd.autoref import BDD

    bdd = BDD()
    for name in _BIT_NAMES:
        bdd.declare(name)
    expr = bdd.false
    for lits in paths_for_class1:
        term = bdd.true
        for fidx, negated in lits:
            v = bdd.var(_BIT_NAMES[fidx])
            term &= ~v if negated else v
        expr |= term
    # Pretty-print the DNF.
    return _bdd_to_python(bdd, expr)


def _bdd_to_python(bdd, node) -> str:
    """Translate ``dd``'s ``ite(cond, a, b) / FALSE / TRUE`` form to a
    Python expression using ``and``/``or``/``not``.
    """
    expr = bdd.to_expr(node)
    # Simple recursive substitutions; dd nests ite so we walk repeatedly.
    while "ite(" in expr:
        i = expr.index("ite(")
        depth = 0
        j = i + 4
        args = []
        start = j
        while j < len(expr):
            if expr[j] == "(":
                depth += 1
            elif expr[j] == ")" and depth > 0:
                depth -= 1
            elif (expr[j] == "," and depth == 0) or (expr[j] == ")" and depth == 0):
                args.append(expr[start:j].strip())
                start = j + 1
                if expr[j] == ")":
                    break
            j += 1
        if len(args) != 3:
            break
        cond, a, b = args
        replacement = f"({a} if {cond} else {b})"
        expr = expr[:i] + replacement + expr[j + 1 :]
    expr = expr.replace("FALSE", "False").replace("TRUE", "True")
    return expr


def _emit(expr: str) -> str:
    params = ", ".join(_BIT_NAMES)
    return (
        '"""BDD-minimised CBT discriminator — AUTOGENERATED.\n'
        "\n"
        "A decision tree was trained on six binary features; the\n"
        "accepting (gold=1) paths were unioned as a DNF, then passed\n"
        "through a BDD for canonical minimisation. The result below is\n"
        "the smallest equivalent boolean expression.\n"
        '"""\n\n'
        f"def predict({params}) -> bool:\n"
        f"    return bool({expr})\n"
    )


def main() -> int:
    print("loading cam-cst/cbt CN train…", file=sys.stderr)
    X, y = _dataset()
    print(f"  examples: {len(X)}", file=sys.stderr)
    clf = _learn_tree(X, y)
    paths = _tree_paths(clf)
    accepting = [lits for lits, cls in paths if cls == 1]
    print(f"  accepting paths: {len(accepting)}", file=sys.stderr)
    expr = _minimise(accepting)
    sys.stdout.write(_emit(expr))
    return 0


if __name__ == "__main__":
    import sys as _sys

    _sys.exit(main())
