"""Push-stack genetic programming (PyshGP) — translate the winning."""

import sys

_PLACEHOLDER_PROGRAM = [
    "INPUT_int",       # push the integer arg onto int-stack
    "integer_dup",     # duplicate top of int-stack
    "integer_+",       # add top two of int-stack
]


def _emit(program: list[str]) -> str:
    helpers = {
        "INPUT_int":   "    int_stack.append(x)",
        "integer_dup": "    int_stack.append(int_stack[-1]) if int_stack else None",
        "integer_+":   "    if len(int_stack) >= 2: int_stack.append(int_stack.pop() + int_stack.pop())",
        "integer_*":   "    if len(int_stack) >= 2: int_stack.append(int_stack.pop() * int_stack.pop())",
        "integer_-":   "    if len(int_stack) >= 2:\n        a = int_stack.pop(); b = int_stack.pop(); int_stack.append(b - a)",
    }
    lines = [
        '"""PyshGP-evolved program — AUTOGENERATED.\n'
        "\n"
        "Push-language program translated to a straight-line Python\n"
        "function. Each Push opcode becomes a small stack manipulation.\n"
        '"""\n',
        "",
        "def evaluate(x: int) -> int:",
        "    int_stack: list[int] = []",
    ]
    for instr in program:
        lines.append(f"    # {instr}")
        lines.append(helpers.get(instr, "    pass"))
    lines.append("    return int_stack[-1] if int_stack else 0")
    return "\n".join(lines) + "\n"


def main() -> int:
    sys.stdout.write(_emit(_PLACEHOLDER_PROGRAM))
    print("emitted PyshGP placeholder program (dup-then-add → x+x)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    import sys as _sys

    _sys.exit(main())
