"""DreamCoder-style program induction — emit a small λ-library + each."""

import sys

_DSL = """
LIBRARY = {
    'is_vowel':   lambda c: c.lower() in 'aeiou',
    'is_alpha':   lambda c: c.isalpha(),
    'to_upper':   lambda c: c.upper(),
    'identity':   lambda c: c,
}
"""


_PROGRAM = """
def solve(s: str) -> str:
    # Discovered by exhaustive composition over the library:
    return ''.join(
        LIBRARY['to_upper'](c) if not LIBRARY['is_vowel'](c) and LIBRARY['is_alpha'](c)
        else c
        for c in s
    )
"""


def _emit() -> str:
    return (
        '"""DreamCoder-style λ-library demo — AUTOGENERATED.\n'
        "\n"
        "Library + a discovered program for the task \"uppercase consonants\".\n"
        "The full DreamCoder wake-sleep loop is OCaml-backed; this is the\n"
        "shape of the artifact it would produce, written in idiomatic Python.\n"
        '"""\n'
        f"{_DSL}\n"
        f"{_PROGRAM}\n"
    )


def main() -> int:
    sys.stdout.write(_emit())
    print("emitted DreamCoder demo (library + solving program)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    import sys as _sys

    _sys.exit(main())
