"""Symbolic regression via PySR — emit a Python ``score()`` function."""

import sys

from evals._hf import load_rows
from dispatch.primitives.cloze_features import FEATURE_NAMES, cloze_features

_MAX_TRAIN_ROWS = 2000
_NITERATIONS = 40
_BINOPS = ("+", "*", "-", "/")
_UNOPS = ("neg", "abs")


def _build_dataset():
    import numpy as np

    X: list[list[int]] = []
    y: list[float] = []
    rows = load_rows("cam-cst/cbt", "CN", split="train")
    kept = 0
    for row in rows:
        if kept >= _MAX_TRAIN_ROWS:
            break
        sentences = row.get("sentences") or []
        question = row.get("question") or ""
        options = list(row.get("options") or ())
        answer = row.get("answer") or ""
        if not question or len(options) != 10 or not answer:
            continue
        if "XXXXX" not in question:
            continue
        prompt = (" ".join(sentences) + "\n" + question) if sentences else question
        gold = answer.strip().lower()
        added = 0
        for opt in options:
            feats = cloze_features(prompt, opt)
            if feats is None:
                continue
            X.append(list(feats))
            y.append(1.0 if opt.strip().lower() == gold else 0.0)
            added += 1
        if added == 10:
            kept += 1
    return np.array(X, dtype=float), np.array(y, dtype=float)


def _emit(expr_py: str) -> str:
    feature_args = ", ".join(FEATURE_NAMES)
    return (
        '"""PySR-emitted CBT candidate scorer — AUTOGENERATED.\n'
        "\n"
        "Trained via ``ml/train_pysr.py``.\n"
        "Do not hand-edit; rerun the trainer instead.\n"
        f"\nArguments order: ({feature_args})\n"
        '"""\n\n'
        "import math\n\n\n"
        f"def score({feature_args}):\n"
        f"    return {expr_py}\n"
    )


def main() -> int:
    from pysr import PySRRegressor

    print("loading cam-cst/cbt CN train…", file=sys.stderr)
    X, y = _build_dataset()
    print(f"  examples: {len(X)}", file=sys.stderr)
    model = PySRRegressor(
        niterations=_NITERATIONS,
        binary_operators=list(_BINOPS),
        unary_operators=["neg", "abs"],
        model_selection="best",
        verbosity=0,
    )
    model.fit(X, y, variable_names=list(FEATURE_NAMES))
    best = model.get_best()
    expr = str(best["sympy_format"])
    # sympy uses ** for power; Python supports this verbatim.
    print(f"best expression: {expr}", file=sys.stderr)
    sys.stdout.write(_emit(expr))
    return 0


if __name__ == "__main__":
    import sys as _sys

    _sys.exit(main())
