"""Sequitur grammar induction — emit a context-free grammar as a."""

import sys

from evals._hf import load_rows
from dispatch.text import tokenize


def _sequitur(tokens: list[str]) -> dict[str, list[str]]:
    """Tiny Sequitur-ish factoriser.

    Real Sequitur enforces digram-uniqueness and rule-utility
    invariants; this stripped version just folds adjacent repeats —
    enough to show the artifact shape.
    """
    rules: dict[str, list[str]] = {"S": list(tokens)}
    next_id = 0
    changed = True
    while changed:
        changed = False
        for name, body in list(rules.items()):
            for i in range(len(body) - 1):
                a, b = body[i], body[i + 1]
                # find a repeated digram somewhere later in *any* rule
                for other_name, other in rules.items():
                    found = False
                    for j in range(len(other) - 1):
                        if (other_name, j) == (name, i):
                            continue
                        if other[j] == a and other[j + 1] == b:
                            found = True
                            break
                    if found:
                        new_name = f"R{next_id}"
                        next_id += 1
                        rules[new_name] = [a, b]
                        for n, body2 in rules.items():
                            new_body = []
                            k = 0
                            while k < len(body2):
                                if k + 1 < len(body2) and body2[k] == a and body2[k + 1] == b:
                                    new_body.append(new_name)
                                    k += 2
                                else:
                                    new_body.append(body2[k])
                                    k += 1
                            rules[n] = new_body
                        changed = True
                        break
                if changed:
                    break
            if changed:
                break
        if next_id > 50:
            break
    return rules


def _emit(rules: dict[str, list[str]]) -> str:
    body_lines = [f"    {k!r}: {v!r}," for k, v in sorted(rules.items())]
    body = "\n".join(body_lines)
    return (
        '"""Sequitur-induced grammar — AUTOGENERATED.\n'
        "\n"
        "Built from the token stream of a CBT-CN passage via\n"
        "``ml/train_sequitur.py``. The grammar reproduces the original\n"
        "sequence exactly when expanded from ``S``.\n"
        '"""\n\n'
        "RULES: dict[str, list[str]] = {\n"
        f"{body}\n"
        "}\n\n\n"
        "def expand(name: str = 'S') -> list[str]:\n"
        "    body = RULES.get(name, [name])\n"
        "    out: list[str] = []\n"
        "    for sym in body:\n"
        "        if sym in RULES:\n"
        "            out.extend(expand(sym))\n"
        "        else:\n"
        "            out.append(sym)\n"
        "    return out\n"
    )


def main() -> int:
    rows = load_rows("cam-cst/cbt", "CN", split="train")
    first = next(iter(rows))
    sentences = first.get("sentences") or []
    tokens = tokenize(" ".join(sentences[:3]))[:60]
    rules = _sequitur(tokens)
    print(f"  tokens: {len(tokens)} → rules: {len(rules)}", file=sys.stderr)
    sys.stdout.write(_emit(rules))
    return 0


if __name__ == "__main__":
    import sys as _sys

    _sys.exit(main())
