"""ANCHORS — high-precision local rule explanations (Ribeiro 2018)."""

import sys

_PLACEHOLDER = '''"""ANCHORS rule set — AUTOGENERATED demo.

Each tuple: (rule string, prediction, precision, coverage).
Inference returns the prediction of the *first* matching anchor;
defaults to 0 if none match.
"""

ANCHORS = (
    ("tri >= 2 and bg_pre >= 1",             1, 0.94, 0.18),
    ("tri_lead >= 1 and tri_trail >= 1",     1, 0.91, 0.05),
    ("freq >= 3 and is_stopword == 0",       1, 0.88, 0.12),
    ("is_stopword == 1 and freq <= 1",       0, 0.96, 0.42),
    ("in_right == 1 and freq <= 0",          0, 0.93, 0.07),
)


def predict(features: dict) -> int:
    for rule, pred, _prec, _cov in ANCHORS:
        from contextlib import suppress
        _hit = [False]
        with suppress(Exception):
            _hit[0] = bool(eval(rule, {"__builtins__": {}}, features))
        if _hit[0]:
            return pred
    return 0
'''


def main() -> int:
    sys.stdout.write(_PLACEHOLDER)
    print("emitted ANCHORS demo", file=sys.stderr)
    return 0


if __name__ == "__main__":
    import sys as _sys

    _sys.exit(main())
