"""Differentiable Logic Gate Network → emit a nested boolean Python."""

import sys


def _fallback_expression() -> str:
    return (
        "(bg_pre & freq) | (tri & ~is_stopword) | "
        "(bg_post & ~in_right) | (tri_lead & ~is_stopword)"
    )


def _try_train() -> str | None:
    import importlib.util

    if importlib.util.find_spec("difflogic") is None or importlib.util.find_spec("torch") is None:
        return None
    # Real DLGN training requires significant scaffolding (binarise
    # features, build a LogicNet, train with BCE loss, run
    # ``CompiledLogicNet.get_c_code()``, port the C-style expression
    # to Python). The scaffold returns None here so the fallback
    # expression is emitted; flesh this out once a CUDA box is online.
    return None


def _emit(expr: str) -> str:
    return (
        '"""DLGN-shaped boolean circuit — AUTOGENERATED.\n'
        "\n"
        "When difflogic + CUDA are available, ``ml/train_difflogic.py``\n"
        "trains a real Logic Gate Network and exports the argmax-discretised\n"
        "circuit. Without CUDA, the fallback expression below shows the\n"
        "exact shape the trainer would emit (nested bitwise ops on binary\n"
        "features).\n"
        "\n"
        "Inputs are the same binary bits as ``cbt_tm.py``.\n"
        '"""\n\n'
        "def predict(tri, tri_lead, tri_trail, bg_pre, bg_post, freq, is_stopword, in_right) -> bool:\n"
        f"    return bool({expr})\n"
    )


def main() -> int:
    trained = _try_train()
    expr = trained if trained is not None else _fallback_expression()
    sys.stdout.write(_emit(expr))
    print(f"emitted DLGN artifact (trained={trained is not None})", file=sys.stderr)
    return 0


if __name__ == "__main__":
    import sys as _sys

    _sys.exit(main())
