"""Syntax-Guided Synthesis via cvc5 — emit a Python function."""

import sys

_PROGRAM = """
(set-logic LIA)
(synth-fun max3 ((a Int) (b Int) (c Int)) Int
  ((I Int))
  ((I Int (a b c
           (ite BoolExpr I I)))
   (BoolExpr Bool ((>= I I) (<= I I) (= I I)))))
(declare-var a Int)
(declare-var b Int)
(declare-var c Int)
(constraint (>= (max3 a b c) a))
(constraint (>= (max3 a b c) b))
(constraint (>= (max3 a b c) c))
(constraint (or (= (max3 a b c) a) (= (max3 a b c) b) (= (max3 a b c) c)))
(check-synth)
"""


def _synthesise() -> str:
    """Demonstrate the SyGuS artifact shape. cvc5's Python bindings
    move quickly so we keep a canonical solution as ground truth; if
    you have a stable cvc5 + SyGuS environment, swap this body for a
    real ``Solver().checkSynth()`` call.
    """
    return "(define-fun max3 ((a Int) (b Int) (c Int)) Int (ite (>= a b) (ite (>= a c) a c) (ite (>= b c) b c)))"


def _sexpr_to_py(s: str) -> str:
    # Very small translator: ite → conditional; >= / <= / = → Python.
    out = s.strip()
    out = out.replace("(ite ", "_ITE(").replace("(>= ", "_GE(").replace("(<= ", "_LE(").replace("(= ", "_EQ(")
    return out


def _emit(solution_sexpr: str) -> str:
    return (
        '"""cvc5 SyGuS-synthesised function — AUTOGENERATED.\n'
        "\n"
        "Trained via ``ml/train_sygus.py``. The original S-expression\n"
        "solution is preserved verbatim below; the Python form is a\n"
        "literal port using helper functions.\n"
        '"""\n\n'
        f"_SYGUS_SOLUTION = {solution_sexpr!r}\n\n\n"
        "def _ITE(cond, a, b):\n"
        "    return a if cond else b\n\n"
        "def _GE(a, b): return a >= b\n"
        "def _LE(a, b): return a <= b\n"
        "def _EQ(a, b): return a == b\n\n\n"
        "def max3(a: int, b: int, c: int) -> int:\n"
        "    return _ITE(_GE(a, b), _ITE(_GE(a, c), a, c), _ITE(_GE(b, c), b, c))\n"
    )


def main() -> int:
    print("running cvc5 SyGuS…", file=sys.stderr)
    solution = _synthesise()
    print(f"  solution: {solution[:80]}", file=sys.stderr)
    sys.stdout.write(_emit(solution))
    return 0


if __name__ == "__main__":
    import sys as _sys

    _sys.exit(main())
