"""Symbolic regression via gplearn — emit a Python ``score()`` function."""

import sys

from evals._hf import load_rows
from dispatch.primitives.cloze_features import FEATURE_NAMES, cloze_features

_MAX_TRAIN_ROWS = 3000
_GENERATIONS = 20
_POPULATION = 1000
_TREE_DEPTH = 4

# Map gplearn operator names → Python source.
_OP_PY: dict[str, str] = {
    "add": "({a} + {b})",
    "sub": "({a} - {b})",
    "mul": "({a} * {b})",
    "div": "(({a}) / ({b}) if {b} else 0.0)",
    "neg": "(-{a})",
    "abs": "abs({a})",
    "max": "max({a}, {b})",
    "min": "min({a}, {b})",
}


def _build_dataset():
    import numpy as np

    X: list[list[int]] = []
    y: list[float] = []
    rows = load_rows("cam-cst/cbt", "CN", split="train")
    kept = 0
    for row in rows:
        if kept >= _MAX_TRAIN_ROWS:
            break
        sentences = row.get("sentences") or []
        question = row.get("question") or ""
        options = list(row.get("options") or ())
        answer = row.get("answer") or ""
        if not question or len(options) != 10 or not answer:
            continue
        if "XXXXX" not in question:
            continue
        prompt = (" ".join(sentences) + "\n" + question) if sentences else question
        gold = answer.strip().lower()
        added = 0
        for opt in options:
            feats = cloze_features(prompt, opt)
            if feats is None:
                continue
            X.append(list(feats))
            y.append(1.0 if opt.strip().lower() == gold else 0.0)
            added += 1
        if added == 10:
            kept += 1
    return np.array(X, dtype=float), np.array(y, dtype=float)


def _tree_to_python(program) -> str:
    """Translate a gplearn ``_Program`` to pure-Python source.

    ``program.program`` is a flat list of operators and feature indices.
    """
    stack: list[str] = []
    for node in reversed(program.program):
        if hasattr(node, "name"):
            name = node.name
            arity = node.arity
            args = [stack.pop() for _ in range(arity)]
            template = _OP_PY.get(name)
            if template is None:
                expr = f"{name}({', '.join(args)})"
            elif arity == 1:
                expr = template.format(a=args[0])
            else:
                expr = template.format(a=args[0], b=args[1])
            stack.append(expr)
        elif isinstance(node, int):
            stack.append(f"x[{node}]")
        else:
            stack.append(repr(float(node)))
    return stack[-1]


def _emit(program) -> str:
    feature_list = ", ".join(repr(n) for n in FEATURE_NAMES)
    expr = _tree_to_python(program)
    return (
        '"""gplearn-emitted CBT candidate scorer — AUTOGENERATED.\n'
        "\n"
        "Trained via ``ml/train_gplearn.py`` (symbolic regression).\n"
        "Do not hand-edit; rerun the trainer instead.\n"
        "\n"
        f"Feature order: ({feature_list},)\n"
        '"""\n\n'
        "def score(x):\n"
        f"    return {expr}\n"
    )


def main() -> int:
    from gplearn.genetic import SymbolicRegressor

    print("loading cam-cst/cbt CN train…", file=sys.stderr)
    X, y = _build_dataset()
    print(f"  examples: {len(X)}", file=sys.stderr)
    reg = SymbolicRegressor(
        population_size=_POPULATION,
        generations=_GENERATIONS,
        function_set=("add", "sub", "mul", "neg", "abs", "max", "min"),
        init_depth=(2, _TREE_DEPTH),
        random_state=0,
        verbose=0,
    )
    reg.fit(X, y)
    program = reg._program
    print(f"discovered expression length: {len(program.program)}", file=sys.stderr)
    sys.stdout.write(_emit(program))
    return 0


if __name__ == "__main__":
    import sys as _sys

    _sys.exit(main())
