"""RobustFill-style programs-by-example — emit a regex-replace DSL."""

import re
import sys

_TASK = [
    ("  Hello, World!  ", "hello world"),
    ("  Foo  Bar  Baz  ", "foo bar baz"),
    ("  Tom  Riddle ", "tom riddle"),
]


_CANDIDATE_PROGRAMS: list[list[tuple[str, ...]]] = [
    [("trim",), ("lower",)],
    [("trim",), ("lower",), ("replace", r"\s+", " ")],
    [("trim",), ("lower",), ("replace", r"[^a-z ]", "")],
    [("trim",), ("lower",), ("replace", r"\s+", " "), ("replace", r"[^a-z ]", "")],
]


def _apply(op, s: str) -> str:
    if op[0] == "trim":
        return s.strip()
    if op[0] == "lower":
        return s.lower()
    if op[0] == "upper":
        return s.upper()
    if op[0] == "replace":
        return re.sub(op[1], op[2], s)
    return s


def _run(program: list[tuple], s: str) -> str:
    for op in program:
        s = _apply(op, s)
    return s


def _emit(program: list[tuple]) -> str:
    parts = [f"        x = _apply({op!r}, x)" for op in program]
    body = "\n".join(parts)
    return (
        '"""RobustFill-style discovered program — AUTOGENERATED.\n'
        "\n"
        "DSL: replace(regex, repl), lower(s), upper(s), trim(s).\n"
        "Discovered by exhaustive search over short pipelines.\n"
        '"""\n\n'
        "import re\n\n\n"
        "def _apply(op, s):\n"
        "    if op[0] == 'trim': return s.strip()\n"
        "    if op[0] == 'lower': return s.lower()\n"
        "    if op[0] == 'upper': return s.upper()\n"
        "    if op[0] == 'replace': return re.sub(op[1], op[2], s)\n"
        "    return s\n\n\n"
        "def transform(s: str) -> str:\n"
        "    x = s\n"
        f"{body}\n"
        "    return x\n"
    )


def main() -> int:
    best = None
    best_hits = -1
    for prog in _CANDIDATE_PROGRAMS:
        hits = sum(1 for i, o in _TASK if _run(prog, i) == o)
        if hits > best_hits:
            best_hits = hits
            best = prog
    print(f"best program scored {best_hits}/{len(_TASK)}", file=sys.stderr)
    sys.stdout.write(_emit(best))
    return 0


if __name__ == "__main__":
    import sys as _sys

    _sys.exit(main())
