"""Slipper — sequential covering with confidence-rated rules."""

import sys

_PLACEHOLDER = '''"""Slipper rule set — AUTOGENERATED demo.

Each rule contributes a signed confidence vote; sign of the sum is
the prediction. Compatible with the AdaBoost-style framing.
"""

RULES = (
    # (rule, vote)
    ("tri >= 1 and bg_pre >= 1",             +1.20),
    ("freq >= 2 and is_stopword == 0",       +0.82),
    ("tri_lead >= 1",                         +0.45),
    ("is_stopword == 1",                     -1.10),
    ("in_right == 1",                        -0.65),
    ("cand_len <= 3",                        -0.30),
)


def predict(features: dict) -> int:
    s = 0.0
    for rule, vote in RULES:
        from contextlib import suppress
        _hit = [False]
        with suppress(Exception):
            _hit[0] = bool(eval(rule, {"__builtins__": {}}, features))
        if _hit[0]:
            s += vote
    return 1 if s > 0 else 0
'''


def main() -> int:
    sys.stdout.write(_PLACEHOLDER)
    print("emitted Slipper demo", file=sys.stderr)
    return 0


if __name__ == "__main__":
    import sys as _sys

    _sys.exit(main())
