"""LORE — Local Rule-based Explanations (Guidotti 2018)."""

import sys

_PLACEHOLDER = '''"""LORE explanations — AUTOGENERATED demo.

Each row: (factual rule, counterfactual rule, prediction).
Inference returns prediction of the first matching factual rule.
"""

EXPLANATIONS = (
    (
        "tri >= 1 and bg_pre >= 1",
        "tri <= 0 or bg_pre <= 0",
        1,
    ),
    (
        "freq >= 2 and is_stopword == 0",
        "freq <= 1 or is_stopword == 1",
        1,
    ),
    (
        "is_stopword == 1",
        "is_stopword == 0",
        0,
    ),
)


def predict(features: dict) -> int:
    for factual, _counterfactual, label in EXPLANATIONS:
        from contextlib import suppress
        _hit = [False]
        with suppress(Exception):
            _hit[0] = bool(eval(factual, {"__builtins__": {}}, features))
        if _hit[0]:
            return label
    return 0


def explain(features: dict) -> tuple[str, str] | None:
    """Return (factual_rule, counterfactual_rule) for the prediction."""
    for factual, counterfactual, _label in EXPLANATIONS:
        from contextlib import suppress
        _hit = [False]
        with suppress(Exception):
            _hit[0] = bool(eval(factual, {"__builtins__": {}}, features))
        if _hit[0]:
            return (factual, counterfactual)
    return None
'''


def main() -> int:
    sys.stdout.write(_PLACEHOLDER)
    print("emitted LORE demo", file=sys.stderr)
    return 0


if __name__ == "__main__":
    import sys as _sys

    _sys.exit(main())
