"""Popper ILP — emit a learned Prolog/Python predicate."""

import sys

_PROLOG = """
% learned by Popper: classify a number as 'is_double' iff y = 2x
is_double(X, Y) :- mul(X, 2, Y).
"""


def _emit() -> str:
    return (
        '"""Popper ILP-learned predicate — AUTOGENERATED.\n'
        "\n"
        "Prolog source preserved verbatim plus a Python predicate.\n"
        '"""\n\n'
        f"PROLOG = {_PROLOG.strip()!r}\n\n\n"
        "def is_double(x: int, y: int) -> bool:\n"
        "    return y == x * 2\n"
    )


def main() -> int:
    sys.stdout.write(_emit())
    print("emitted Popper demo", file=sys.stderr)
    return 0


if __name__ == "__main__":
    import sys as _sys

    _sys.exit(main())
