"""Explainable Boosting Machine (interpret-ml) → per-feature lookup."""

import sys

from evals._hf import load_rows
from dispatch.primitives.cloze_features import FEATURE_NAMES, cloze_features

_MAX_TRAIN_ROWS = 3000


def _build_dataset():
    import numpy as np

    X: list[list[int]] = []
    y: list[int] = []
    rows = load_rows("cam-cst/cbt", "CN", split="train")
    kept = 0
    for row in rows:
        if kept >= _MAX_TRAIN_ROWS:
            break
        sentences = row.get("sentences") or []
        question = row.get("question") or ""
        options = list(row.get("options") or ())
        answer = row.get("answer") or ""
        if not question or len(options) != 10 or not answer:
            continue
        if "XXXXX" not in question:
            continue
        prompt = (" ".join(sentences) + "\n" + question) if sentences else question
        gold = answer.strip().lower()
        added = 0
        for opt in options:
            feats = cloze_features(prompt, opt)
            if feats is None:
                continue
            X.append(list(feats))
            y.append(1 if opt.strip().lower() == gold else 0)
            added += 1
        if added == 10:
            kept += 1
    return np.array(X, dtype=float), np.array(y, dtype=int)


def _emit(intercept: float, shapes: list[tuple[list[float], list[float]]]) -> str:
    lines = [
        '"""EBM scorer — AUTOGENERATED.',
        "",
        "Trained via ``ml/train_ebm.py``. One additive contribution per",
        "feature, lookup-by-bin. Do not hand-edit; rerun the trainer.",
        "",
        f"Feature order: {FEATURE_NAMES}",
        '"""',
        "",
        f"INTERCEPT = {intercept!r}",
        "",
        "SHAPES = (",
    ]
    for name, (bins, contribs) in zip(FEATURE_NAMES, shapes):
        bin_repr = "[" + ", ".join(f"{b!r}" for b in bins) + "]"
        contrib_repr = "[" + ", ".join(f"{c!r}" for c in contribs) + "]"
        lines.append(f"    ({name!r}, {bin_repr}, {contrib_repr}),")
    lines.append(")")
    lines.append("")
    lines.append("")
    lines.append("def score(features):")
    lines.append("    out = INTERCEPT")
    lines.append("    for i, (_, bins, contribs) in enumerate(SHAPES):")
    lines.append("        v = features[i]")
    lines.append("        idx = 0")
    lines.append("        for cut in bins:")
    lines.append("            if v < cut: break")
    lines.append("            idx += 1")
    lines.append("        out += contribs[min(idx, len(contribs) - 1)]")
    lines.append("    return out")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    from interpret.glassbox import ExplainableBoostingClassifier

    print("loading cam-cst/cbt CN train…", file=sys.stderr)
    X, y = _build_dataset()
    print(f"  examples: {len(X)}", file=sys.stderr)
    ebm = ExplainableBoostingClassifier(interactions=0, max_bins=16)
    ebm.fit(X, y)
    intercept = float(ebm.intercept_[0]) if hasattr(ebm.intercept_, "__getitem__") else float(ebm.intercept_)
    shapes: list[tuple[list[float], list[float]]] = []
    for term_idx in range(len(FEATURE_NAMES)):
        bins = list(map(float, ebm.bins_[term_idx][0]))
        contribs = list(map(float, ebm.term_scores_[term_idx]))
        shapes.append((bins, contribs))
    sys.stdout.write(_emit(intercept, shapes))
    return 0


if __name__ == "__main__":
    import sys as _sys

    _sys.exit(main())
