"""Symbolic regression via PyOperon (C++ Operon with Python bindings)."""

import sys

from evals._hf import load_rows
from dispatch.primitives.cloze_features import FEATURE_NAMES, cloze_features

_MAX_TRAIN_ROWS = 1500


def _build_dataset():
    import numpy as np

    X: list[list[int]] = []
    y: list[float] = []
    rows = load_rows("cam-cst/cbt", "CN", split="train")
    kept = 0
    for row in rows:
        if kept >= _MAX_TRAIN_ROWS:
            break
        sentences = row.get("sentences") or []
        question = row.get("question") or ""
        options = list(row.get("options") or ())
        answer = row.get("answer") or ""
        if not question or len(options) != 10 or not answer:
            continue
        if "XXXXX" not in question:
            continue
        prompt = (" ".join(sentences) + "\n" + question) if sentences else question
        gold = answer.strip().lower()
        added = 0
        for opt in options:
            feats = cloze_features(prompt, opt)
            if feats is None:
                continue
            X.append(list(feats))
            y.append(1.0 if opt.strip().lower() == gold else 0.0)
            added += 1
        if added == 10:
            kept += 1
    return np.array(X, dtype=float), np.array(y, dtype=float)


def _fallback_expression() -> str:
    return "tri + 0.5 * tri_lead + 0.5 * tri_trail + 0.3 * bg_pre + 0.3 * bg_post"


def _emit(expr: str) -> str:
    args = ", ".join(FEATURE_NAMES)
    return (
        '"""PyOperon-emitted CBT scorer — AUTOGENERATED.\n'
        "\n"
        "Trained via ``ml/train_pyoperon.py``. On platforms without\n"
        "PyOperon wheels, the trainer falls back to a placeholder.\n"
        '"""\n\n'
        f"def score({args}):\n"
        f"    return {expr}\n"
    )


def main() -> int:
    import importlib.util

    if importlib.util.find_spec("pyoperon.sklearn") is None:
        print("pyoperon unavailable on this platform — emitting placeholder", file=sys.stderr)
        sys.stdout.write(_emit(_fallback_expression()))
        return 0
    from pyoperon.sklearn import SymbolicRegressor

    X, y = _build_dataset()
    print(f"  examples: {len(X)}", file=sys.stderr)
    reg = SymbolicRegressor(
        n_threads=1, max_evaluations=int(2e5), random_state=0
    )
    reg.fit(X, y)
    sympy_expr = str(reg.get_model_string(reg.model_, precision=4))
    sys.stdout.write(_emit(sympy_expr))
    print(f"best: {sympy_expr[:80]}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    import sys as _sys

    _sys.exit(main())
