"""Induce a minimal DFA from positive/negative example token sequences."""

import sys

from evals._hf import load_rows

_MAX_ROWS = 1500
_QUOTES = set('"“”\'')


def _abstract(ch: str) -> str:
    if ch in _QUOTES:
        return "Q"
    if ch.isspace():
        return "S"
    if ch.isalpha():
        return "L"
    if ch.isdigit():
        return "D"
    return "P"


def _examples() -> tuple[list[str], list[str]]:
    pos: list[str] = []
    neg: list[str] = []
    rows = load_rows("cam-cst/cbt", "CN", split="train")
    kept = 0
    for row in rows:
        if kept >= _MAX_ROWS:
            break
        for sent in (row.get("sentences") or []):
            tokens = "".join(_abstract(c) for c in sent[:24])
            if not tokens:
                continue
            if "Q" in tokens:
                pos.append(tokens)
            else:
                neg.append(tokens)
        kept += 1
    return pos, neg


def _learn_dfa(pos: list[str], neg: list[str]):
    from aalpy.learning_algs import run_RPNI

    data = [(tuple(s), True) for s in pos] + [(tuple(s), False) for s in neg]
    dfa = run_RPNI(data, automaton_type="dfa", print_info=False)
    return dfa


def _emit(dfa) -> str:
    # AALpy DFAs have ``states`` (each with ``state_id``, ``is_accepting``,
    # ``transitions: dict[str, State]``).
    state_id_to_idx = {s.state_id: i for i, s in enumerate(dfa.states)}
    table: list[dict[str, int]] = []
    final: set[int] = set()
    for s in dfa.states:
        idx = state_id_to_idx[s.state_id]
        if s.is_accepting:
            final.add(idx)
        row: dict[str, int] = {}
        for sym, nxt in s.transitions.items():
            row[sym] = state_id_to_idx[nxt.state_id]
        # ensure we have an entry at the right index
        while len(table) <= idx:
            table.append({})
        table[idx] = row
    start_idx = state_id_to_idx[dfa.initial_state.state_id]
    return (
        '"""RPNI-induced DFA — dialog vs. narrator — AUTOGENERATED.\n'
        "\n"
        "Trained via ``ml/train_aalpy_dfa.py``. Symbols: Q=quote, L=letter,\n"
        "S=space, P=punct, D=digit.\n"
        '"""\n\n'
        f"START: int = {start_idx}\n"
        f"TABLE: tuple[dict[str, int], ...] = {tuple(table)!r}\n"
        f"FINAL: frozenset[int] = frozenset({set(final)!r})\n"
        "\n"
        "\n"
        "def _abstract(ch: str) -> str:\n"
        "    if ch in '\\\"\\u201c\\u201d\\'': return 'Q'\n"
        "    if ch.isspace(): return 'S'\n"
        "    if ch.isalpha(): return 'L'\n"
        "    if ch.isdigit(): return 'D'\n"
        "    return 'P'\n"
        "\n"
        "\n"
        "def accepts(text: str) -> bool:\n"
        "    s = START\n"
        "    for ch in text[:24]:\n"
        "        sym = _abstract(ch)\n"
        "        nxt = TABLE[s].get(sym, -1)\n"
        "        if nxt < 0: return False\n"
        "        s = nxt\n"
        "    return s in FINAL\n"
    )


def main() -> int:
    print("loading cam-cst/cbt CN train…", file=sys.stderr)
    pos, neg = _examples()
    print(f"  pos={len(pos)} neg={len(neg)}", file=sys.stderr)
    print("running RPNI…", file=sys.stderr)
    dfa = _learn_dfa(pos[:600], neg[:600])
    print(f"  states: {len(dfa.states)}", file=sys.stderr)
    sys.stdout.write(_emit(dfa))
    return 0


if __name__ == "__main__":
    import sys as _sys

    _sys.exit(main())
