"""RIPPER (Repeated Incremental Pruning to Produce Error Reduction) —."""

import sys

from dispatch.primitives.cloze_features import FEATURE_NAMES

_PLACEHOLDER_RULES = [
    ("tri >= 1 and bg_pre >= 1", 1),
    ("freq >= 2 and is_stopword == 0", 1),
    ("True", 0),
]


def _emit(rules) -> str:
    lines = [
        '"""RIPPER-learned ordered rule set — AUTOGENERATED.\n'
        "\n"
        "First matching rule wins; final rule is the default.\n"
        '"""\n',
        f"FEATURE_NAMES = {tuple(FEATURE_NAMES)!r}",
        "",
        "",
        "def predict(features: dict) -> int:",
    ]
    for cond, cls in rules:
        lines.append(f"    if eval({cond!r}, {{'__builtins__': {{}}}}, features):")
        lines.append(f"        return {cls}")
    lines.append("    return 0")
    return "\n".join(lines) + "\n"


def main() -> int:
    sys.stdout.write(_emit(_PLACEHOLDER_RULES))
    print("emitted RIPPER placeholder", file=sys.stderr)
    return 0


if __name__ == "__main__":
    import sys as _sys

    _sys.exit(main())
