"""LASSO / elastic-net sparse linear regression — emit the coefficient."""

import sys

from evals._hf import load_rows
from dispatch.primitives.cloze_features import FEATURE_NAMES, cloze_features

_MAX_TRAIN_ROWS = 3000


def _dataset():
    import numpy as np

    X: list[list[int]] = []
    y: list[float] = []
    rows = load_rows("cam-cst/cbt", "CN", split="train")
    kept = 0
    for row in rows:
        if kept >= _MAX_TRAIN_ROWS:
            break
        sentences = row.get("sentences") or []
        question = row.get("question") or ""
        options = list(row.get("options") or ())
        answer = row.get("answer") or ""
        if not question or len(options) != 10 or not answer:
            continue
        if "XXXXX" not in question:
            continue
        prompt = (" ".join(sentences) + "\n" + question) if sentences else question
        gold = answer.strip().lower()
        added = 0
        for opt in options:
            feats = cloze_features(prompt, opt)
            if feats is None:
                continue
            X.append(list(feats))
            y.append(1.0 if opt.strip().lower() == gold else 0.0)
            added += 1
        if added == 10:
            kept += 1
    return np.array(X, dtype=float), np.array(y, dtype=float)


def main() -> int:
    from sklearn.linear_model import Lasso

    X, y = _dataset()
    clf = Lasso(alpha=0.01, max_iter=5000)
    clf.fit(X, y)
    coefs = {name: float(c) for name, c in zip(FEATURE_NAMES, clf.coef_) if abs(c) > 1e-6}
    intercept = float(clf.intercept_)
    out = (
        '"""LASSO sparse linear scorer — AUTOGENERATED.\n'
        "\n"
        "score = intercept + sum(weight * feature) over non-zero weights.\n"
        '"""\n\n'
        f"INTERCEPT = {intercept!r}\n"
        f"WEIGHTS = {coefs!r}\n\n\n"
        "def score(features: dict) -> float:\n"
        "    return INTERCEPT + sum(features[k] * v for k, v in WEIGHTS.items())\n"
    )
    sys.stdout.write(out)
    print(f"non-zero coefficients: {len(coefs)}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    import sys as _sys

    _sys.exit(main())
