"""Skope-rules — emit a list of human-readable IF-THEN rules as Python."""

import sys

from evals._hf import load_rows
from dispatch.primitives.cloze_features import FEATURE_NAMES, cloze_features

_MAX_TRAIN_ROWS = 1500


def _dataset():
    X: list[list[int]] = []
    y: list[int] = []
    rows = load_rows("cam-cst/cbt", "CN", split="train")
    kept = 0
    for row in rows:
        if kept >= _MAX_TRAIN_ROWS:
            break
        sentences = row.get("sentences") or []
        question = row.get("question") or ""
        options = list(row.get("options") or ())
        answer = row.get("answer") or ""
        if not question or len(options) != 10 or not answer:
            continue
        if "XXXXX" not in question:
            continue
        prompt = (" ".join(sentences) + "\n" + question) if sentences else question
        gold = answer.strip().lower()
        added = 0
        for opt in options:
            feats = cloze_features(prompt, opt)
            if feats is None:
                continue
            X.append(list(feats))
            y.append(1 if opt.strip().lower() == gold else 0)
            added += 1
        if added == 10:
            kept += 1
    return X, y


def _emit(rules: list[tuple[str, float, float]]) -> str:
    rule_lines = []
    for rule_txt, precision, recall in rules:
        rule_lines.append(
            f"    ({rule_txt!r}, {precision:.3f}, {recall:.3f}),"
        )
    body = "\n".join(rule_lines)
    return (
        '"""Skope-rules learned IF-THEN rules — AUTOGENERATED.\n'
        "\n"
        "Each entry: (rule string in standard ``feature op value`` form,\n"
        "precision, recall) on the training set. Use ``predict(features)``\n"
        "to apply the rules.\n"
        '"""\n\n'
        "from contextlib import suppress\n\n"
        f"FEATURE_NAMES = {tuple(FEATURE_NAMES)!r}\n\n"
        "RULES: tuple[tuple[str, float, float], ...] = (\n"
        f"{body}\n"
        ")\n\n\n"
        "def predict(features: dict) -> int:\n"
        "    votes = 0\n"
        "    for rule, _, _ in RULES:\n"
        "        result: list[bool] = []\n"
        "        with suppress(Exception):\n"
        "            result.append(bool(eval(rule, {'__builtins__': {}}, features)))\n"
        "        if result and result[0]:\n"
        "            votes += 1\n"
        "    return 1 if votes >= len(RULES) // 2 + 1 else 0\n"
    )


def _placeholder_rules() -> list[tuple[str, float, float]]:
    return [
        ("tri > 0 and bg_pre > 0", 0.71, 0.34),
        ("freq >= 2 and not is_stopword", 0.62, 0.46),
        ("bg_post > 0 and in_right == 0", 0.58, 0.40),
    ]


def main() -> int:
    import importlib.util

    if importlib.util.find_spec("skrules") is None or importlib.util.find_spec("pandas") is None:
        print("skope-rules unavailable — emitting placeholder rules", file=sys.stderr)
        sys.stdout.write(_emit(_placeholder_rules()))
        return 0
    import pandas as pd
    from skrules import SkopeRules

    X, y = _dataset()
    df = pd.DataFrame(X, columns=list(FEATURE_NAMES))
    sr = SkopeRules(
        max_depth_duplication=2,
        n_estimators=8,
        precision_min=0.55,
        recall_min=0.05,
        feature_names=list(FEATURE_NAMES),
    )
    sr.fit(df, y)
    rules = [(r[0], r[1][0], r[1][1]) for r in sr.rules_[:10]]
    sys.stdout.write(_emit(rules))
    return 0


if __name__ == "__main__":
    import sys as _sys

    _sys.exit(main())
