"""Generic PrefixSpan / SPADE pattern mining via PAMI — emit patterns."""

import sys

from evals._hf import load_rows
from dispatch.text import tokenize

_MAX_ROWS = 2000
_MIN_SUPPORT = 50


def _build_transactions() -> list[list[str]]:
    out: list[list[str]] = []
    rows = load_rows("cam-cst/cbt", "CN", split="train")
    kept = 0
    for row in rows:
        if kept >= _MAX_ROWS:
            break
        sentences = row.get("sentences") or []
        tokens = [t.lower() for t in tokenize(" ".join(sentences[:3]))]
        if tokens:
            out.append(tokens[:30])
        kept += 1
    return out


def _emit(patterns: list[tuple[tuple[str, ...], int]]) -> str:
    body = "\n".join(f"    ({p!r}, {s})," for p, s in patterns[:200])
    return (
        '"""PrefixSpan-mined sequence patterns — AUTOGENERATED.\n'
        "\n"
        "Top-200 frequent subsequences from CBT-CN train passages via\n"
        "``ml/train_pami.py``. Each entry: (token-tuple, support count).\n"
        '"""\n\n'
        "PATTERNS: tuple[tuple[tuple[str, ...], int], ...] = (\n"
        f"{body}\n"
        ")\n"
    )


def main() -> int:
    import importlib.util

    if importlib.util.find_spec("PAMI.sequentialPattern.basic.prefixSpan") is None:
        print("PAMI unavailable — emitting empty patterns", file=sys.stderr)
        sys.stdout.write(_emit([]))
        return 0
    from PAMI.sequentialPattern.basic import prefixSpan

    transactions = _build_transactions()
    print(f"  transactions: {len(transactions)}", file=sys.stderr)
    # PAMI expects newline-separated transactions in a file.
    import tempfile

    with tempfile.NamedTemporaryFile("w", suffix=".txt", delete=False) as f:
        for t in transactions:
            f.write(" ".join(t) + "\n")
        path = f.name
    miner = prefixSpan.PrefixSpan(iFile=path, minSup=_MIN_SUPPORT)
    miner.mine()
    raw = miner.getPatterns()
    patterns: list[tuple[tuple[str, ...], int]] = []
    for pattern_str, support in raw.items():
        toks = tuple(pattern_str.strip().split())
        patterns.append((toks, int(support)))
    patterns.sort(key=lambda p: -p[1])
    sys.stdout.write(_emit(patterns))
    return 0


if __name__ == "__main__":
    import sys as _sys

    _sys.exit(main())
