"""SAT-based minimal DFA induction (``dfa-identify``)."""

import sys

from evals._hf import load_rows

_MAX_ROWS = 300
_QUOTES = set('"“”\'')


def _abstract(ch: str) -> str:
    if ch in _QUOTES: return "Q"
    if ch.isspace(): return "S"
    if ch.isalpha(): return "L"
    if ch.isdigit(): return "D"
    return "P"


def _examples():
    pos: list[tuple[str, ...]] = []
    neg: list[tuple[str, ...]] = []
    rows = load_rows("cam-cst/cbt", "CN", split="train")
    kept = 0
    for row in rows:
        if kept >= _MAX_ROWS:
            break
        for sent in (row.get("sentences") or [])[:2]:
            tokens = tuple(_abstract(c) for c in sent[:12])
            if not tokens:
                continue
            (pos if "Q" in tokens else neg).append(tokens)
        kept += 1
    return pos[:80], neg[:80]


def _learn(pos, neg):
    from dfa_identify import find_dfa

    return find_dfa(accepting=pos, rejecting=neg)


def _emit(dfa) -> str:
    states = sorted(dfa.states())
    sid = {s: i for i, s in enumerate(states)}
    alphabet = sorted(dfa.inputs)
    table: list[dict[str, int]] = []
    final: set[int] = set()
    for s in states:
        row: dict[str, int] = {}
        for a in alphabet:
            row[a] = sid[dfa.transition((a,), start=s)]
        table.append(row)
        if dfa.label(()) if s == dfa.start else False:
            pass  # placeholder
        if dfa.label((), start=s):
            final.add(sid[s])
    return (
        '"""SAT-minimal DFA — AUTOGENERATED via ``ml/train_dfa_identify.py``.\n'
        '"""\n\n'
        f"START: int = {sid[dfa.start]}\n"
        f"TABLE = {tuple(table)!r}\n"
        f"FINAL = frozenset({set(final)!r})\n"
        "\n"
        "def accepts(seq):\n"
        "    s = START\n"
        "    for sym in seq:\n"
        "        nxt = TABLE[s].get(sym, -1)\n"
        "        if nxt < 0: return False\n"
        "        s = nxt\n"
        "    return s in FINAL\n"
    )


def main() -> int:
    print("loading data…", file=sys.stderr)
    pos, neg = _examples()
    print(f"  pos={len(pos)} neg={len(neg)}", file=sys.stderr)
    print("running SAT solver…", file=sys.stderr)
    dfa = _learn(pos, neg)
    sys.stdout.write(_emit(dfa))
    return 0


if __name__ == "__main__":
    import sys as _sys

    _sys.exit(main())
