"""C4.5 / C5.0 decision tree — emit nested if/else."""

import sys

from evals._hf import load_rows
from dispatch.primitives.cloze_features import FEATURE_NAMES, cloze_features

_MAX_TRAIN_ROWS = 5000
_TREE_MAX_DEPTH = 6


def _dataset():
    X: list[list[int]] = []
    y: list[int] = []
    rows = load_rows("cam-cst/cbt", "CN", split="train")
    kept = 0
    for row in rows:
        if kept >= _MAX_TRAIN_ROWS:
            break
        sentences = row.get("sentences") or []
        question = row.get("question") or ""
        options = list(row.get("options") or ())
        answer = row.get("answer") or ""
        if not question or len(options) != 10 or not answer:
            continue
        if "XXXXX" not in question:
            continue
        prompt = (" ".join(sentences) + "\n" + question) if sentences else question
        gold = answer.strip().lower()
        added = 0
        for opt in options:
            feats = cloze_features(prompt, opt)
            if feats is None:
                continue
            X.append(list(feats))
            y.append(1 if opt.strip().lower() == gold else 0)
            added += 1
        if added == 10:
            kept += 1
    return X, y


def main() -> int:
    import m2cgen
    from sklearn.tree import DecisionTreeClassifier

    print("loading cam-cst/cbt CN train…", file=sys.stderr)
    X, y = _dataset()
    print(f"  examples: {len(X)}", file=sys.stderr)
    clf = DecisionTreeClassifier(
        criterion="entropy",  # the C4.5/C5.0 split criterion
        max_depth=_TREE_MAX_DEPTH,
        min_samples_leaf=200,
        class_weight={0: 1.0, 1: 9.0},
        random_state=0,
    )
    clf.fit(X, y)
    body = m2cgen.export_to_python(clf, function_name="_raw_score")
    feature_list = ", ".join(repr(n) for n in FEATURE_NAMES)
    out = (
        '"""C4.5/C5.0-style decision tree (entropy split) — AUTOGENERATED.\n'
        "\n"
        f"Feature order: ({feature_list},)\n"
        '"""\n\n'
        f"{body}\n\n"
        "def score(features):\n"
        "    raw = _raw_score(list(features))\n"
        "    return raw[1] if isinstance(raw, list) and len(raw) == 2 else float(raw)\n"
    )
    sys.stdout.write(out)
    return 0


if __name__ == "__main__":
    import sys as _sys

    _sys.exit(main())
