"""Decision stump — 1-level decision tree, the simplest weak learner."""

import sys

_PLACEHOLDER = '''"""Decision stump — AUTOGENERATED demo.

Single split on the most informative feature.
"""

FEATURE = "tri"
THRESHOLD = 0.5


def predict(features: dict) -> int:
    return 1 if features.get(FEATURE, 0) > THRESHOLD else 0
'''


def main() -> int:
    sys.stdout.write(_PLACEHOLDER)
    print("emitted decision stump demo", file=sys.stderr)
    return 0


if __name__ == "__main__":
    import sys as _sys

    _sys.exit(main())
