"""M5 model trees — regression tree with a linear regression at each."""

import sys

_PLACEHOLDER = '''"""M5 model tree — AUTOGENERATED demo.

Three leaves; each leaf is `intercept + sum(w_i * x_i)`.

Leaf structure:
  IF tri >= 1   THEN  LinearLeaf_1
  IF bg_pre >= 1 THEN  LinearLeaf_2
  ELSE                 LinearLeaf_3
"""

LEAVES = {
    "L1": {"intercept": 0.62, "weights": {"tri": 0.31, "freq": 0.09}},
    "L2": {"intercept": 0.41, "weights": {"bg_pre": 0.22, "bg_post": 0.18}},
    "L3": {"intercept": 0.08, "weights": {"freq": 0.04, "tri_lead": 0.07}},
}


def predict(features: dict) -> float:
    if features.get("tri", 0) >= 1:
        leaf = LEAVES["L1"]
    elif features.get("bg_pre", 0) >= 1:
        leaf = LEAVES["L2"]
    else:
        leaf = LEAVES["L3"]
    return leaf["intercept"] + sum(
        w * features.get(k, 0) for k, w in leaf["weights"].items()
    )
'''


def main() -> int:
    sys.stdout.write(_PLACEHOLDER)
    print("emitted M5 model tree demo", file=sys.stderr)
    return 0


if __name__ == "__main__":
    import sys as _sys

    _sys.exit(main())
