"""LILO — DreamCoder + LLM library-renaming pass."""

import sys

_LIBRARY = '''
def is_consonant(ch: str) -> bool:
    """Renamed by LILO from the DreamCoder primitive ``f6``."""
    return ch.isalpha() and ch.lower() not in 'aeiou'


def all_uppercase(s: str) -> str:
    """Renamed by LILO from the DreamCoder library entry ``r2``."""
    return s.upper()
'''


_PROGRAM = '''
def solve(s: str) -> str:
    """LILO renames + reorders DreamCoder's tree into idiomatic Python."""
    return ''.join(all_uppercase(c) if is_consonant(c) else c for c in s)
'''


def _emit() -> str:
    return (
        '"""LILO-style renamed library demo — AUTOGENERATED.\n'
        "\n"
        "DreamCoder λ-calculus output passed through an LLM rename pass\n"
        "to produce idiomatic Python.\n"
        '"""\n'
        f"{_LIBRARY}\n"
        f"{_PROGRAM}\n"
    )


def main() -> int:
    sys.stdout.write(_emit())
    print("emitted LILO demo", file=sys.stderr)
    return 0


if __name__ == "__main__":
    import sys as _sys

    _sys.exit(main())
