"""TPSR (Transformer-PSR) — emit the discovered sympy expression as."""

import sys

_EXPR = "x0**2 + 2 * x0 * x1 + x1**2"


def _emit() -> str:
    return (
        '"""TPSR-style expression — AUTOGENERATED.\n'
        "\n"
        "Example of a closed-form output from TPSR (pretrained transformer\n"
        "PSR + MCTS at decode). Real integration requires the research\n"
        "code at deep-symbolic-mathematics/TPSR.\n"
        '"""\n\n'
        "def score(x0, x1):\n"
        f"    return {_EXPR}\n"
    )


def main() -> int:
    sys.stdout.write(_emit())
    print("emitted TPSR placeholder expression", file=sys.stderr)
    return 0


if __name__ == "__main__":
    import sys as _sys

    _sys.exit(main())
