"""Mine frequent token-prefix → next-token patterns and emit them as."""

import sys
from collections import Counter, defaultdict

from evals._hf import load_rows
from dispatch.text import tokenize
from dispatch.primitives.lexicons import STOPWORDS

_MAX_ROWS = 8000
_MIN_TOTAL = 5
_MIN_DOMINANT_SHARE = 0.5


def _build_counts() -> dict[tuple[str, str], Counter[str]]:
    counts: dict[tuple[str, str], Counter[str]] = defaultdict(Counter)
    rows = load_rows("cam-cst/cbt", "CN", split="train")
    kept = 0
    for row in rows:
        if kept >= _MAX_ROWS:
            break
        sentences = row.get("sentences") or []
        question = row.get("question") or ""
        if not question or "XXXXX" not in question:
            continue
        answer = (row.get("answer") or "").strip().lower()
        if not answer:
            continue
        left, _ = question.split("XXXXX", 1)
        toks = [t.lower() for t in tokenize(left)]
        if len(toks) < 2:
            continue
        # XXXXX is preceded by (toks[-2], toks[-1]); the gold is the
        # answer that fills XXXXX.
        prev2, prev = toks[-2], toks[-1]
        counts[(prev2, prev)][answer] += 1
        kept += 1
    # also feed sentence-level patterns from the passages for breadth
    return counts


def _filter(counts: dict[tuple[str, str], Counter[str]]) -> dict[tuple[str, str], str]:
    out: dict[tuple[str, str], str] = {}
    for prefix, c in counts.items():
        total = sum(c.values())
        if total < _MIN_TOTAL:
            continue
        best, best_count = c.most_common(1)[0]
        if best.lower() in STOPWORDS:
            continue
        if best_count / total < _MIN_DOMINANT_SHARE:
            continue
        out[prefix] = best
    return out


def _emit(patterns: dict[tuple[str, str], str]) -> str:
    body_lines = ["    " + repr(k) + ": " + repr(v) + "," for k, v in sorted(patterns.items())]
    body = "\n".join(body_lines)
    return (
        '"""PrefixSpan-style (prev2, prev) → next patterns mined from CBT-CN train.\n'
        "AUTOGENERATED via ``ml/train_prefixspan.py``. Do not hand-edit.\n"
        '"""\n\n'
        "PATTERNS: dict[tuple[str, str], str] = {\n"
        f"{body}\n"
        "}\n"
        "\n\n"
        "def lookup(prev2: str, prev: str) -> str | None:\n"
        "    return PATTERNS.get((prev2.lower(), prev.lower()))\n"
    )


def main() -> int:
    print("loading cam-cst/cbt CN train…", file=sys.stderr)
    counts = _build_counts()
    print(f"  (prev2, prev) pairs: {len(counts)}", file=sys.stderr)
    patterns = _filter(counts)
    print(f"  kept high-confidence patterns: {len(patterns)}", file=sys.stderr)
    sys.stdout.write(_emit(patterns))
    return 0


if __name__ == "__main__":
    import sys as _sys

    _sys.exit(main())
