"""Scallop (Datalog + provenance) — emit a Datalog program as Python."""

import sys

_PROGRAM = """
rel is_a("giraffe", "mammal")
rel is_a("mammal", "animal")
rel name(a, b) :- name(a, c), is_a(c, b)
"""


def _emit() -> str:
    return (
        '"""Scallop-shaped Datalog rule set — AUTOGENERATED.\n'
        "\n"
        "The full Scallop framework compiles a .scl file with provenance\n"
        "semirings. This artifact is the same rule set as Python data\n"
        "plus a forward-chaining evaluator.\n"
        '"""\n\n'
        f"SCALLOP_PROGRAM = {_PROGRAM.strip()!r}\n\n"
        "FACTS = {\n"
        '    ("is_a", ("giraffe", "mammal")),\n'
        '    ("is_a", ("mammal",   "animal")),\n'
        "}\n\n\n"
        "def name(a: str, b: str) -> bool:\n"
        "    # name(a, b) :- is_a(a, b) | exists c: is_a(a, c) ^ name(c, b)\n"
        '    if ("is_a", (a, b)) in FACTS:\n'
        "        return True\n"
        "    for kind, (x, c) in FACTS:\n"
        '        if kind == "is_a" and x == a and name(c, b):\n'
        "            return True\n"
        "    return False\n"
    )


def main() -> int:
    sys.stdout.write(_emit())
    print("emitted Scallop demo (rules + forward-chaining evaluator)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    import sys as _sys

    _sys.exit(main())
